const fs=require('fs'),path=require('path'),vm=require('vm'),{webcrypto}=require('crypto');
const root=__dirname,config=fs.readFileSync(path.join(root,'js/config.js'),'utf8'),admin=fs.readFileSync(path.join(root,'js/11-rayo-cash-report-module.js'),'utf8'),publicApp=fs.readFileSync(path.join(root,'cash-report/js/app.js'),'utf8'),calls=[];
let responders=[],uuidNo=0;
const response=(status,body)=>({ok:status>=200&&status<300,status,async text(){return JSON.stringify(body)}});
const sandbox={window:{RAYO_ENV:{API_ORIGIN:'https://test.local',API_PREFIX:'/api/v1.0',API_CONTROLLER:'/RayoData',TIMEOUT_MS:100}},fetch:async(url,options={})=>{calls.push({url,options});const fn=responders.shift();if(!fn)throw Error('unexpected fetch');return fn(url,options)},AbortController,Uint8Array,crypto:{...webcrypto,randomUUID:()=>`00000000-0000-4000-8000-${String(++uuidNo).padStart(12,'0')}`},setTimeout,clearTimeout,console,Date,Math,JSON,Object,Array,Map,Set,WeakSet,Error,String,Number,Boolean,Promise,encodeURIComponent};sandbox.window.window=sandbox.window;sandbox.globalThis=sandbox;vm.createContext(sandbox);new vm.Script(config).runInContext(sandbox);const gateway=sandbox.window.RAYO_API_GATEWAY,checks=[];function ok(name,v){if(!v)throw Error('FAIL '+name);checks.push(name)}async function rejects(name,fn,test){let e;try{await fn()}catch(x){e=x}ok(name,e&&test(e))}
(async()=>{
 const report={id:'CASH-0001',date:'1405/06/01',cashierId:'CASHIER-0001',netReceivable:1000};
 responders.push(()=>response(200,{items:[report],page:1,pageSize:100,total:1,totalPages:1,version:3}));await gateway.queryCollection({module:'cashreport',collection:'reports',dateField:'date',from:'1405-06-01',to:'1405-06-30',sortBy:'date',descending:true,page:1,pageSize:100});const query=JSON.parse(calls.at(-1).options.body);ok('Load اولیه و فیلتر تاریخ',query.collection==='reports'&&query.dateField==='date'&&query.from==='1405-06-01'&&query.page===1&&query.pageSize===100);
 responders.push(()=>response(200,{items:[],page:2,pageSize:500,total:501,totalPages:2,version:3}));await gateway.queryCollection({module:'cashreport',collection:'reports',page:2,pageSize:900});ok('صفحه‌بندی با سقف 500',JSON.parse(calls.at(-1).options.body).pageSize===500);
 for(const operation of ['insert','update','archive']){responders.push(()=>response(200,{ok:true,version:4}));await gateway.mutateRecord({module:'cashreport',collection:'reports',operation,recordId:report.id,idField:'id',requestId:`req-${operation}`,data:report});ok(operation,JSON.parse(calls.at(-1).options.body).operation===operation)}
 const before=calls.length;responders.push(()=>response(409,{code:'version_conflict'}));await rejects('Version Conflict بدون retry',()=>gateway.mutateRecord({module:'cashreport',collection:'reports',operation:'update',recordId:report.id,idField:'id',requestId:'conflict',data:report}),e=>e.status===409&&calls.length===before+1);
 responders.push(()=>{throw new TypeError('Failed to fetch')});await rejects('قطع شبکه',()=>gateway.queryCollection({module:'cashreport',collection:'reports',filters:{cashierId:'x'}}),e=>e.code==='network_error');
 ok('Admin فقط reports را Mutate می‌کند',/collection:CR_REPORT_COLLECTION/.test(admin)&&!admin.includes("mutateRecord({module:'cashreport',collection:'cashiers'"));
 ok('مرجع صندوقدار Query چندصفحه‌ای است',admin.includes("collection:'cashiers'")&&admin.includes('page<=first.totalPages')&&publicApp.includes("queryItems('cashiers'"));
 ok('Public بدون Save کامل reports',!publicApp.slice(publicApp.indexOf('async function saveReport'),publicApp.indexOf('function fillCashiers')).includes('postState('));
 ok('Archive فیزیکی نیست',admin.includes("operation:'archive'")&&!/crDeleteReport[\s\S]{0,300}\.filter\(/.test(admin));
 ok('دوبار کلیک و Retry پایدار',admin.includes('crQueryState.submitting||crQueryState.readOnly')&&admin.includes('requestId:pending.requestId')&&publicApp.includes('reportSubmitting'));
 ok('لغو درخواست خروج',admin.includes("nav.dataset.view!=='cashReport'")&&admin.includes('controller?.abort()'));
 ok('عدم Auto-save',!admin.slice(admin.indexOf('async function crEnsureReportsLoaded'),admin.indexOf('function crTabs')).includes('saveModule(')&&!publicApp.slice(publicApp.indexOf('async function loadApi'),publicApp.indexOf('async function loadState')).includes('saveModule('));
 ok('بخش‌های جانبی روی Load Save قدیمی',admin.includes("CashStorage.load()")&&admin.includes("CashStorage.save(cashState)"));
 ok('نمایش و فیلتر reports از Query است',admin.includes('async function crApplyReportFilters')&&admin.includes('crQueryReports({force:true,all:true})')&&admin.includes('cashState.reports=result.items'));
 ok('ویرایش reports رکورد کامل Queryشده را Mutate می‌کند',admin.includes("const old=cashUI.editingId?cashState.reports.find")&&admin.includes("operation:old?'update':'insert'"));
 console.log(`PASS ${checks.length}`);checks.forEach(x=>console.log('  ✓ '+x));
})().catch(e=>{console.error(e);process.exitCode=1});
