'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const read=f=>fs.readFileSync(f,'utf8');
const code=read('js/46-inventory-operations-v10-12.js');
function setup(){
 const state={settings:{mainLocationId:'main'},locations:[{id:'main',name:'انبار'}],stockReceipts:[],inventoryMovements:[],stocktakes:[]},pricing={ingredients:[{id:'tea',name:'چای',code:'T1',recipeUnit:'کیلو',packageQuantity:5,lastPurchasePriceToman:700000}]},els={},saves=[],errors=[];
 for(const [id,value] of Object.entries({v1012RecDate:'1405/06/26',v1012RecIng:'tea',v1012RecLoc:'main',v1012RecQty:'۲٫۳۴',v1012RecTotal:'۱۲۰٬۰۰۰',v1012RecPriceMode:'unit'}))els[id]={value};
 const c={console,URLSearchParams,location:{pathname:'/qa.html',search:''},sessionStorage:{getItem:()=> 'manager'},document:{readyState:'loading',querySelector:()=>null,querySelectorAll:()=>[],createElement:()=>({}),head:{appendChild(){}},addEventListener(){},getElementById:id=>els[id]},setTimeout(){},getInventoryState:()=>state,getPricingState:()=>pricing,RayoInventoryV10:{locations:()=>state.locations,openModal:(...args)=>c.modal=args},RAYO_API_GATEWAY:{createRequestId:()=> 'qa-1',saveModule:async(m)=>saves.push(m)},toast:m=>errors.push(m),renderView(){},closeModal(){}};c.window=c;vm.createContext(c);vm.runInContext(code.replace('function body(){','window.testReceipt=receiptV2;function body(){'),c);return {c,state,pricing,els,saves,errors,api:c.RayoInventoryV1012};
}
(async()=>{
 let t=setup();assert.equal(t.saves.length,0);await t.api.saveReceipt(true);assert.equal(t.state.stockReceipts.length,1);assert.equal(t.state.stockReceipts[0].quantity,2.34);assert.equal(t.state.stockReceipts[0].unitCostToman,120000);assert.equal(t.state.stockReceipts[0].totalPriceToman,280800);assert.deepEqual(t.saves,['inventory']);assert.equal(t.pricing.ingredients[0].lastPurchasePriceToman,700000,'do not replace package price with receipt total');
 t=setup();t.els.v1012RecPriceMode.value='total';t.els.v1012RecQty.value='2.5';t.els.v1012RecTotal.value='250000';await t.api.saveReceipt(false);assert.equal(t.state.stockReceipts[0].unitCostToman,100000);
 for(const [field,value] of [['v1012RecQty','bad'],['v1012RecTotal','-5'],['v1012RecTotal','bad']]){t=setup();t.els[field].value=value;await t.api.saveReceipt(false);assert.equal(t.saves.length,0)}
 t=setup();t.els.v1012RecUnit={};t.els.v1012RecItemHint={};t.els.v1012RecValue={};t.api.filterReceiptItems('T1');assert(t.els.v1012RecIng.size>1,'search keeps matching options expanded');t.api.receiptItemChanged();assert.equal(t.els.v1012RecIng.size,1,'selection collapses the list');assert.equal(t.els.v1012RecIng.value,'tea');t.api.filterReceiptItems('T1');assert(t.els.v1012RecIng.size>1,'typing reopens results even with a prior selection');t.api.receiptItemChanged();assert(t.els.v1012RecUnit.textContent.includes('کیلو'));assert(t.els.v1012RecItemHint.textContent.includes('چای'));
 t.state.stockReceipts=[{id:'a',status:'posted',sourceType:'DIRECT_ENTRY'},{id:'b',status:'void',sourceType:'DIRECT_ENTRY'}];let html=t.c.testReceipt();assert(/data-status="void" hidden/.test(html));assert(!html.includes('<th>کد</th>'));assert(html.includes('title="T1"'));assert(html.includes('data-large-page'));
 const rows=[{dataset:{status:'posted',search:'چای',rayoPageHidden:'1'}},{dataset:{status:'void',search:'چای'}}];t.c.document.querySelectorAll=s=>s==='[data-v1012-receipt-row]'?rows:[];t.api.receiptSearch('چای');assert.equal(rows[0].hidden,false);assert.equal(rows[1].hidden,true);assert(!rows[0].dataset.rayoPageHidden);t.api.receiptStatus('all');assert(rows.every(x=>!x.hidden));t.api.receiptStatus('void');assert(rows[0].hidden&&!rows[1].hidden);
 t=setup();t.state.stockReceipts=[{id:'a',date:'1405/06/26',status:'posted'}];t.els.v1012VoidReceiptReason={value:'خطای ثبت'};await t.api.confirmVoidReceipt('a');assert.equal(t.saves.length,0,'manager checkbox required');t.els.v1012VoidManagerConfirm={checked:true};await t.api.confirmVoidReceipt('a');assert.equal(t.saves.length,0,'backup required');t.c.sessionStorage.getItem=()=>null;t.api.openVoidReceipt('a');assert(!t.c.modal,'staff cannot open manager action');
 t=setup();t.state.stockReceipts=[{id:'a',ingredientId:'tea',locationId:'main',date:'1405/06/26',status:'posted'}];t.state.inventoryMovements=[{id:'m',sourceKey:'receipt:a',status:'posted'}];t.els.v1012VoidReceiptReason={value:'خطای ثبت'};t.els.v1012VoidManagerConfirm={checked:true};t.c.URL={createObjectURL:()=> 'blob:test',revokeObjectURL(){}};t.c.Blob=class{};t.c.document.createElement=()=>({click(){}});t.api.downloadReceiptBackup('a');t.state.stocktakes.push({id:'count',date:'1405/06/26',locationId:'main',status:'approved',lines:[{ingredientId:'tea'}]});await t.api.confirmVoidReceipt('a');assert.equal(t.saves.length,0,'dependencies are rechecked after preview');t.state.stocktakes=[];await t.api.confirmVoidReceipt('a');assert.equal(t.state.stockReceipts[0].status,'void');assert.equal(t.state.inventoryMovements[0].status,'void');assert.equal(t.state.stockReceipts.length,1,'no physical delete');assert.equal(t.state.stockReceipts[0].voidedBy,'manager');await t.api.confirmVoidReceipt('a');assert.equal(t.saves.length,1,'void is idempotent');
 // Details remain read-only and escape stored text; archiving never deletes ledger history.
 t=setup();t.state.stockReceipts=[{id:'a',ingredientId:'tea',locationId:'main',status:'void',notes:'line 1\n<script>bad</script>',voidReason:'ثبت تکراری',voidedBy:'manager',voidedAt:'2026-09-17'}];t.state.inventoryMovements=[{id:'m',sourceKey:'receipt:a',status:'void'}];t.api.viewReceipt('a');assert(t.c.modal[1].includes('&lt;script&gt;'));assert(t.c.modal[1].includes('ثبت تکراری'));assert(t.c.modal[1].includes('line 1\n'));assert.equal(t.saves.length,0);t.state.stockReceipts[0].status='posted';t.api.viewReceipt('a');assert(!t.c.modal[1].includes('ثبت تکراری'));t.api.openReceiptArchive('a',true);await t.api.confirmReceiptArchive();assert.equal(t.saves.length,0,'active receipts cannot be archived');t.state.stockReceipts[0].status='void';t.api.openReceiptArchive('a',true);await t.api.confirmReceiptArchive();assert.equal(t.saves.length,0);t.els.v1012ArchiveConfirm={checked:true};await t.api.confirmReceiptArchive();assert.equal(t.saves.length,0,'archive backup required');t.c.URL={createObjectURL:()=> 'blob:test',revokeObjectURL(){}};t.c.Blob=class{};t.c.document.createElement=()=>({click(){}});t.api.downloadReceiptBackup('a');await Promise.all([t.api.confirmReceiptArchive(),t.api.confirmReceiptArchive()]);assert.equal(t.saves.length,1);assert.equal(t.state.stockReceipts.length,1);assert.equal(t.state.stockReceipts[0].isArchived,true);assert.equal(t.state.stockReceipts[0].voidReason,'ثبت تکراری');assert.equal(t.state.inventoryMovements[0].status,'void');assert.equal(t.state.inventoryMovements.length,1);
 const archivedRow={dataset:{status:'void',search:'tea',archived:'1'}};t.c.document.querySelectorAll=s=>s==='[data-v1012-receipt-row]'?[archivedRow]:[];for(const filter of ['active','all','void']){t.api.receiptStatus(filter);assert(archivedRow.hidden)}t.api.receiptStatus('archived');assert(!archivedRow.hidden);t.api.openReceiptArchive('a',false);t.api.downloadReceiptBackup('a');await t.api.confirmReceiptArchive();assert.equal(t.state.stockReceipts[0].isArchived,false);assert.equal(t.state.stockReceipts[0].status,'void','restore does not reverse the void');
 t.api.openReceiptArchive('a',true);t.api.downloadReceiptBackup('a');const prior=JSON.stringify(t.state);t.c.RAYO_API_GATEWAY.saveModule=async()=>{throw Error('failure')};await t.api.confirmReceiptArchive();assert.equal(JSON.stringify(t.state),prior,'failed archive rolls back');t.c.sessionStorage.getItem=()=>null;t.c.modal=null;t.api.openReceiptArchive('a',true);assert.equal(t.c.modal,null,'manager session required');
 // Exercise the real paginator: a keystroke must not detach the focused row.
 const phase=read('js/44-phase1-polish-v10-10-1.js'),rows2=Array.from({length:30},()=>({hidden:false,dataset:{},isConnected:true,cells:[],querySelector:()=>null,parentElement:{appendChild(){throw Error('Focused row detached')}}})),table={isConnected:true,tBodies:[{rows:rows2}]},node={},listState=new WeakMap([[table,{page:1,pageSize:25,sortIndex:-1,direction:'',original:rows2,meta:{querySelector:()=>node},prev:{},next:{},pageLabel:{}}]]),p={listState,table};vm.createContext(p);vm.runInContext(phase.slice(phase.indexOf('function listRows('),phase.indexOf('function enhanceList(')),p);vm.runInContext('renderList(table);renderList(table)',p);assert.equal(rows2.filter(r=>!r.hidden).length,25);
 // Approved bulk price affects valuation; submitted/legacy counts do not change historical prices.
 const core=read('js/32-inventory-cost-control-v10.js'),a=core.indexOf('function countPriceAt('),b=core.indexOf('function weightedCost(',a),v={A:x=>Array.isArray(x)?x:[],S:x=>String(x??''),N:x=>Number(x)||0,D:x=>x||'',cmp:(a,b)=>a.localeCompare(b),beforeOrEq:(a,b)=>a<=b,strictBefore:(a,b)=>a<b,receiptIsPosted:r=>r.status!=='void',receiptUnitCost:r=>r.unitCostToman,ingredient:()=>({purchaseUnit:'بسته',recipeUnit:'کیلو',packageQuantity:5,lastPurchasePriceToman:500}),inv:{stocktakes:[],stockReceipts:[]},pricing:{ingredientPriceHistory:[]}};v.window=v;v.setTimeout=()=>{};vm.createContext(v);vm.runInContext(read('js/08-rayo-pricing-admin-module.js'),v);vm.runInContext(core.slice(a,b),v);
 v.inv.stocktakes=[{id:'ST-BULK-1',date:'1405/06/24',status:'submitted',lines:[{ingredientId:'tea',purchasePriceToman:600000,unitCost:120000}]}];assert.equal(vm.runInContext("costAtDate('tea','1405/06/26')",v),100);v.inv.stocktakes[0].status='approved';assert.equal(vm.runInContext("costAtDate('tea','1405/06/26')",v),120000);assert.equal(vm.runInContext("costAtDate('tea','1405/06/23')",v),100);v.inv.stockReceipts.push({date:'1405/06/25',ingredientId:'tea',unitCostToman:130000});assert.equal(vm.runInContext("costAtDate('tea','1405/06/26')",v),130000);
 console.log('PASS inventory receipt UI: decimal/unit/total prices, catalog preservation, invalid values, unit labels, status filtering, manager and backup gates, input focus, approved count valuation, no load saves');
})().catch(e=>{console.error(e);process.exitCode=1});
