'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm');
const code=fs.readFileSync('js/46-inventory-operations-v10-12.js','utf8'),base=fs.readFileSync('js/00-base.js','utf8');
const calendar=base.slice(base.indexOf('function jdiv('),base.indexOf('function toJalaali('))+base.match(/function jMonthLength[^\n]+/)[0];
const clone=x=>JSON.parse(JSON.stringify(x));
function setup(){
 const item={id:'i',name:'Soap',code:'123',itemType:'OPERATIONAL_CONSUMABLE',status:'active',recipeUnit:'kg',purchaseUnit:'pack',packageQuantity:5,reorderPoint:5};
 const state={settings:{},unknown:{retained:42},locations:[{id:'main',name:'Main'}],stocktakes:[{id:'st',date:'1405/06/01',locationId:'main',status:'approved',lines:[{ingredientId:'i',actual:20}]}],stockReceipts:[{id:'receipt',ingredientId:'i',locationId:'main',date:'1405/05/01',quantity:5,unitCostToman:100,status:'posted'}],inventoryMovements:[],consumptionRecords:[],operationalConsumptionProfiles:[{id:'p',ingredientId:'i',locationId:'main',unit:'kg',active:true,fixedQuantity:10,fixedDays:10,activityQuantity:0,effectiveFrom:'1405/06/01'}],salesPeriods:[]};
 const pricing={ingredients:[item],menuItems:[{id:'m',name:'Menu'}],recipes:[]},els={},status={valid:true},calls={save:0,load:0},server={data:clone(state),fail:false,drop:false};
 const ctx={console,URLSearchParams,location:{pathname:'/test.html',search:''},sessionStorage:{getItem:()=> 'qa'},document:{readyState:'loading',querySelector:()=>null,createElement:()=>({}),head:{appendChild(){}},addEventListener(){},getElementById:id=>els[id],querySelectorAll:()=>[]},setTimeout(){},getInventoryState:()=>state,getPricingState:()=>pricing,RayoJalali:{today:()=> '1405/06/11'},RayoInventoryV10:{},RayoReorder:{assess:i=>({point:i.reorderPoint??null})},RAYO_API_GATEWAY:{getModuleStatus:()=>({sourceValid:status.valid}),createRequestId:()=>String(calls.save+1),saveModule:async(k,data)=>{calls.save++;if(server.fail)throw Error('offline');server.data=clone(data);if(server.drop)delete server.data.operationalConsumptionProfiles},loadModule:async()=>{calls.load++;return clone(server.data)}},renderView(){},closeModal(){},toast:(m,e)=>{if(e)calls.error=m}};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(calendar,ctx);vm.runInContext(code,ctx);
 return {item,state,pricing,ctx,els,status,calls,server,api:ctx.RayoInventoryV1012,row:()=>ctx.RayoInventoryV1012.forecastRow(item,'main'),profile:state.operationalConsumptionProfiles[0]};
}
function sales(t){for(let d=t.ctx.j2d(1405,6,11)-28;d<=t.ctx.j2d(1405,6,11);d++){const j=t.ctx.d2j(d),date=`${j.jy}/${String(j.jm).padStart(2,'0')}/${String(j.jd).padStart(2,'0')}`;t.state.salesPeriods.push({from:date,to:date,lines:[{menuItemId:'m',quantity:10}]})}}
(async()=>{
 let t=setup(),before=clone(t.state),r=t.row();assert.equal(r.stock,10);assert.equal(r.daily,1);assert.equal(r.cost,3000);assert.equal(r.buyQty,25);assert.equal(r.buyCost,2500);assert.equal(r.remaining,10);assert.equal(r.orderDate,t.ctx.j2d(1405,6,16));assert.deepStrictEqual(t.state,before);assert.equal(t.calls.save,0);
 t.api.forecastChange('horizon',7);assert.equal(t.row().cost,700);t.api.forecastChange('horizon',90);assert.equal(t.row().cost,9000);
 t.profile.fixedQuantity=0;t.profile.activityQuantity=1;t.profile.activityBase=10;t.profile.driver='SOLD_ITEMS';assert.equal(t.row().stock,null);sales(t);assert.equal(t.row().stock,10);assert.equal(t.row().daily,1);t.profile.fixedQuantity=10;assert.equal(t.row().stock,0);assert.equal(t.row().daily,2);t.api.forecastChange('scenario',100);assert.equal(t.row().stock,0);assert.equal(t.row().daily,3);
 t.profile.driver='SELECTED_ITEMS';t.profile.menuItemIds=['m'];assert.equal(t.row().daily,3);t.state.salesPeriods.forEach(p=>p.lines[0].quantity=0);assert.equal(t.row().daily,1);t.status.valid=false;assert.equal(t.row().stock,null);t.status.valid=true;t.state.salesPeriods.pop();assert.equal(t.row().stock,null);
 t=setup();t.state.inventoryMovements.push({ingredientId:'i',date:'1405/06/05',movementType:'PURCHASE_RECEIPT',quantity:5,toLocationId:'main',status:'posted'});assert.equal(t.row().stock,15);t.state.inventoryMovements.push({ingredientId:'i',date:'1405/06/06',movementType:'TRANSFER',quantity:2,fromLocationId:'main',toLocationId:'other',status:'posted'});assert.equal(t.row().stock,13);
 t.state.stocktakes.push({id:'new',date:'1405/06/10',locationId:'main',status:'submitted',lines:[{ingredientId:'i',actual:30}]});assert.equal(t.row().stock,13);t.state.stocktakes[1].status='approved';assert.equal(t.row().stock,29);t.state.stocktakes[1].status='rejected';assert.equal(t.row().stock,13);
 t=setup();t.state.inventoryMovements.push({ingredientId:'i',date:'1405/06/05',movementType:'OTHER_AUTHORIZED',quantity:2,fromLocationId:'main',status:'posted'});assert.equal(t.row().stock,null);t.state.inventoryMovements[0].status='void';assert.equal(t.row().stock,10);
 t.state.stocktakes=[];assert.equal(t.row().stock,null);assert.equal(t.row().endDate,null);t=setup();t.profile.unit='litre';assert.equal(t.row().stock,null);t=setup();t.state.stockReceipts=[];assert.equal(t.row().cost,null);assert.equal(t.row().stock,10);t=setup();delete t.item.packageQuantity;assert.equal(t.row().buyCost,null);
 for(const [actual,status] of [[10,'empty'],[15,'due'],[20,'near'],[30,'enough']]){t=setup();t.state.stocktakes[0].lines[0].actual=actual;r=t.row();assert.equal(r.stock,actual-10);if(status==='empty')assert.equal(r.remaining,0);if(status==='due')assert.equal(r.orderDate,t.ctx.j2d(1405,6,11));if(status==='near')assert.equal(r.priority,2);if(status==='enough')assert.equal(r.priority,5)}
 t=setup();t.item.isArchived=true;assert.equal(t.row().stock,null);t=setup();t.pricing.recipes=[{ingredientId:'i'}];assert.equal(t.row().stock,null);t=setup();t.profile.activityQuantity=1;t.profile.activityBase=10;t.profile.driver='SOLD_ITEMS';sales(t);t.state.salesPeriods.push(clone(t.state.salesPeriods[0]));assert.equal(t.row().daily,null);
 t=setup();t.state.operationalConsumptionProfiles.push({...t.profile,id:'v2',effectiveFrom:'1405/06/06',fixedQuantity:20});assert.equal(t.row().stock,4);
 t=setup();const values={ingredient:'i',location:'main',fixed:'20',days:'10',activity:'',base:'',driver:'SOLD_ITEMS',date:'1405/06/11',note:'test'};Object.entries(values).forEach(([k,value])=>t.els['fc_'+k]={value});t.els.fc_menus={selectedOptions:[]};t.els.fc_active={checked:true};await Promise.all([t.api.forecastSave(),t.api.forecastSave()]);assert.equal(t.calls.save,1);assert.equal(t.calls.load,1);assert.equal(t.state.operationalConsumptionProfiles.length,2);assert.equal(t.state.unknown.retained,42);assert.deepStrictEqual(t.state.operationalConsumptionProfiles,t.server.data.operationalConsumptionProfiles);
 t.els.fc_date.value='1405/06/12';t.server.fail=true;const snapshot=clone(t.state);await t.api.forecastSave();assert.deepStrictEqual(t.state,snapshot);assert(t.calls.error);t.server.fail=false;t.server.drop=true;const attempts=t.calls.save;await t.api.forecastSave();assert.equal(t.calls.save,attempts,'uncertain save blocks retry until reload');assert.deepStrictEqual(t.state,snapshot);
 t=setup();Object.entries(values).forEach(([k,value])=>t.els['fc_'+k]={value});t.els.fc_menus={selectedOptions:[]};t.els.fc_active={checked:true};t.server.drop=true;const unchanged=clone(t.state);await t.api.forecastSave();assert.equal(t.calls.save,1);assert.equal(t.calls.load,1);assert.deepStrictEqual(t.state,unchanged);assert(t.calls.error);
 t=setup();t.els.fc_settings_horizon={value:'60'};t.els.fc_settings_warning={value:'9'};t.els.fc_settings_age={value:'10'};await t.api.forecastSaveSettings();assert.equal(t.state.settings.operationalForecastDays,60);assert.equal(t.calls.load,1);
 t=setup();delete t.state.operationalConsumptionProfiles;t.els.fc_settings_horizon={value:'30'};t.els.fc_settings_warning={value:'7'};t.els.fc_settings_age={value:'14'};await t.api.forecastSaveSettings();assert.equal(t.calls.save,1);assert(!t.calls.error,'old inventory without profiles saves settings');
 t=setup();t.state.settings.operationalCountMaxAgeDays=2;assert.equal(t.row().status,'نیاز به استعلام موجودی');
 t=setup();t.state.operationalConsumptionProfiles.push({...t.profile,id:'future',effectiveFrom:'1405/06/21',fixedQuantity:20});assert.equal(t.row().future,51);assert.equal(t.row().stock,10);assert.equal(t.row().endDate,t.ctx.j2d(1405,6,20)+0.5);
 t=setup();t.profile.activityQuantity=1;t.profile.activityBase=10;t.profile.driver='SOLD_ITEMS';sales(t);t.state.salesPeriods.push({from:'1405/06/11',to:'1405/06/11',source:'SNAPP',lines:[{menuItemId:'m',quantity:1}]});assert.equal(t.row().daily,null,'a missing sales channel is not zero');
 t=setup();t.state.stockReceipts[0].status='void';assert.equal(t.row().cost,null);t=setup();t.state.inventoryMovements.push({ingredientId:'i',date:'1405/06/03',movementType:'TRANSFER',fromLocationId:'main',toLocationId:'other',quantity:2,unitSnapshot:'litre'});assert.equal(t.row().stock,null);
 t=setup();const html=t.api.forecastPanel();assert(html.includes('operational-forecast'));assert(html.includes('تنظیم برآورد مصرف'));assert(html.includes('data-forecast-row'));assert(!html.includes('NaN'));assert.equal(t.calls.save,0);
 t=setup();t.profile.fixedQuantity=10;t.profile.fixedDays=30;t.state.stocktakes[0].date='1405/06/11';t.state.stocktakes[0].lines[0].actual=5;assert.equal(t.row().buyQty,10,'floating point does not add an extra pack');
 console.log('PASS operational forecast: fixed/activity/combined, coverage and true zero, failed load, counts/reset, receipts/transfers, double counting, thresholds, prices/units, scenarios/horizons, versions, no mutations, save/reload, unknown fields, failed save and dropped DTO fields.');
})().catch(e=>{console.error(e);process.exitCode=1});
