'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const read=f=>fs.readFileSync('js/'+f,'utf8'),clone=x=>JSON.parse(JSON.stringify(x));
function harness(path='/suppliers.html'){
 const events={},nodes={},timers=[],requests=[];let posted=null;
 const inv={meta:{initialized:true},settings:{paymentLocations:[{id:'L1',name:'حساب قدیمی',isActive:true,custom:'keep'},{id:'L2',name:'حساب بسته',isActive:false}]},purchaseInvoices:[],supplierPayments:[{id:'P1',supplierId:'S1',amount:10,paymentLocationId:'L1',paymentLocationNameSnapshot:'نام تاریخی',date:'1405/06/01'}]},sup={suppliers:[{id:'S1',code:'S1',company:'آزمایشی',status:'فعال'}],supplierItems:[],items:[],purchaseRequests:[]},pr={ingredients:[],ingredientPriceHistory:[]};
 const c={console,URL,URLSearchParams,Date,Math,Set,Map,Intl,location:{pathname:path,search:'',href:'http://qa'+path},sessionStorage:{getItem:()=> 'qa'},document:{readyState:'loading',currentScript:{defer:true},documentElement:{dataset:{}},body:{querySelectorAll:()=>[]},getElementById:id=>nodes[id]||null,querySelector:()=>({}),querySelectorAll:()=>[],addEventListener:(name,fn)=>(events[name]??=[]).push(fn)},setTimeout:fn=>{timers.push(fn);return timers.length},clearTimeout(){},addEventListener(){},renderView(){},pageHead:(t)=>`<h1>${t}</h1>`,toast:s=>c.lastToast=s,closeModal(){},modalTitle:{},modalBody:{},modalFoot:{},modalBackdrop:{classList:{add(){}}},state:{personnel:[],leaveRequests:[]},titles:{},supplierUI:{tab:'suppliers'},ops:{paymentSupplierId:'S1'},views:{suppliers:()=>'<div class="supplier-module-tabs">legacy</div>',cashReport:()=>'',settings:()=>'<div class="card"><div class="section-head"><h2>فهرست‌های قابل انتخاب</h2></div><div class="form-grid"></div></div><div class="card">کارت بعدی</div>'},getInventoryState:()=>inv,getSupplierState:()=>sup,getPricingState:()=>pr,RayoJalali:{today:()=> '1405/06/29'},RayoIngredientMath:{grossCost:()=>0},RayoOpsAnalytics:{currentPosition:()=>({current:0})},RAYO_API_GATEWAY:{loadModule:async m=>{requests.push('GET '+m);return clone(inv)},saveModule:async(m,d)=>{requests.push('POST '+m);posted=clone(d)}}};
 c.window=c;c.history={replaceState:(a,b,url)=>{c.location.search=new URL(url).search;c.location.href=String(url)},pushState:(a,b,url)=>{c.location.search=new URL(url).search;c.location.href=String(url)}};vm.createContext(c);
 return{c,events,nodes,timers,requests,inv,sup,pr,get posted(){return posted},load:f=>vm.runInContext(read(f),c,{filename:f}),ready:()=>{for(const fn of events.DOMContentLoaded||[])fn()},route:tab=>{c.location.search='?tab='+tab;c.location.href='http://qa'+path+c.location.search;c.supplierUI.tab=tab;return c.views.suppliers()}};
}
(async()=>{
 const h=harness();h.c.document.querySelector=selector=>/^(script|link)/.test(selector)?{}:null;for(const f of ['19-phase2-admin.js','40-rayo-v10-9-comprehensive.js','42-operations-v10-9-2.js','43-central-catalog-v10-10.js','46-inventory-operations-v10-12.js'])h.load(f);h.ready();
 const customDirections={settings:{supplierPaymentDirections:[{value:'refund',label:'برگشت وجه',effect:'receipt',isActive:true}]}};assert.equal(h.c.RayoPaymentOptions.directionSign({direction:'refund'},customDirections),-1,'custom receipt direction has an incoming-funds effect');assert.equal(h.c.RayoPaymentOptions.directionSign({direction:'refund',directionEffect:'payment'},customDirections),1,'historical payment keeps its saved direction effect');
 for(const tab of ['suppliers','relations','dashboard','accounts','payment','orders','invoices','history','json']){const html=h.route(tab),bars=html.match(/<div class="supplier-module-tabs[^>]*>[\s\S]*?<\/div>/g);assert.equal(bars?.length,1,tab+' has exactly one final tab bar');assert(bars[0].includes("supplierTab('dashboard')"),tab+' exposes the dashboard tab');assert(bars[0].includes("supplierTab('invoices')"),tab+' exposes the invoice tab');}
 assert(h.route('invoices').includes('RayoV1092.openInvoiceForm()'),'visible invoice tab opens the new invoice flow');h.c.RayoV1092.openInvoiceForm();assert(h.c.modalBody.innerHTML.includes('بدون تأمین‌کننده (اختیاری)'));
 let html=h.route('payment');assert(html.includes('<option value="" selected>انتخاب تأمین‌کننده</option>'));assert(!html.includes('value="S1" selected'),'stale ops selection cannot preselect a supplier');assert(!html.includes('settings.html?view=settings#payment-locations'),'payment form has no management link');assert(html.includes('پرداخت بدهی')&&html.includes('وصول طلب قبلی'),'configured settlement directions are offered');assert(html.includes('نام تاریخی'),'history retains payment snapshot');assert(!html.includes('<option value="L2"'),'inactive location is not offered for a new payment');
 h.c.location.search='?tab=payment&supplier=S1';html=h.c.views.suppliers();assert(html.includes('value="S1" selected'),'explicit supplier payment shortcut is preserved');h.c.ops.editPaymentId='P1';h.c.location.search='?tab=payment';assert(h.c.views.suppliers().includes('value="S1" selected'),'editing preserves supplier');assert.equal(h.requests.length,0,'renderers never save or seed');
 const s=harness('/settings.html');s.load('19-phase2-admin.js');await s.c.p2ReloadPaymentLocations();const settingsHtml=s.c.views.settings();assert(settingsHtml.includes('p2AddPaymentLocation()'));assert(settingsHtml.includes('p2AddPaymentDirection()'));assert(settingsHtml.includes("p2RemovePaymentOption(this.closest('tr'),'location')"));assert(settingsHtml.indexOf('محل‌های وجه')<settingsHtml.indexOf('کارت بعدی'),'payment lists stay inside the selectable-lists card');let removed=false,active={checked:true};s.c.p2RemovePaymentOption({dataset:{paymentLocation:'L1'},querySelector:()=>active,remove:()=>removed=true},'location');assert.equal(active.checked,false,'used payment location is deactivated');assert.equal(removed,false,'used payment location is not deleted');s.c.p2RemovePaymentOption({dataset:{paymentLocation:'L2'},querySelector:()=>active,remove:()=>removed=true},'location');assert(removed,'unused payment location can be removed');const before=JSON.stringify(s.inv);assert.equal(s.c.RayoPaymentLocations.all({}).length,0,'empty configuration has no automatic bank defaults');assert.equal(JSON.stringify(s.inv),before,'location and direction lookup is read-only');
 let rows=[{id:'L1',name:'حساب جدید',active:true},{id:'L2',name:'حساب بسته',active:false},{id:'',name:'تنخواه تازه',active:true}],directions=[{value:'payment',label:'پرداخت بدهی',effect:'payment',active:true},{value:'receipt',label:'وصول طلب قبلی',effect:'receipt',active:true},{value:'',label:'برگشت وجه',effect:'receipt',active:true}];const tableRows=selector=>selector.startsWith('#p2PaymentLocations')?rows.map(x=>({dataset:{paymentLocation:x.id},querySelector:sel=>sel==='.p2-location-name'?{value:x.name}:{checked:x.active}})):directions.map(x=>({dataset:{paymentDirection:x.value},querySelector:sel=>sel==='.p2-direction-label'?{value:x.label}:sel==='.p2-direction-effect'?{value:x.effect}:{checked:x.active}}));s.c.document.querySelectorAll=tableRows;s.inv.purchaseInvoices.push({id:'ADDED-AFTER-SETTINGS-LOAD'});await s.c.p2SavePaymentLocations();assert(s.posted);assert.equal(s.posted.settings.paymentLocations[0].id,'L1');assert.equal(s.posted.settings.paymentLocations[0].name,'حساب جدید');assert.equal(s.posted.settings.paymentLocations[0].custom,'keep');assert.equal(s.posted.settings.paymentLocations[1].isActive,false);assert.equal(s.posted.settings.paymentLocations.length,3);assert.equal(s.posted.settings.supplierPaymentDirections.length,3);assert.equal(s.posted.settings.supplierPaymentDirections[2].effect,'receipt');assert.equal(s.posted.supplierPayments[0].paymentLocationNameSnapshot,'نام تاریخی');assert.equal(s.posted.purchaseInvoices[0].id,'ADDED-AFTER-SETTINGS-LOAD','fresh read preserves intervening invoices');assert.equal(JSON.stringify(s.inv.settings.paymentLocations),JSON.stringify(JSON.parse(before).settings.paymentLocations),'save does not mutate old cached object');
 const conflict=harness('/settings.html');conflict.load('19-phase2-admin.js');await conflict.c.p2ReloadPaymentLocations();conflict.c.document.querySelectorAll=tableRows;conflict.inv.settings.paymentLocations[0].name='تغییر هم‌زمان';await conflict.c.p2SavePaymentLocations();assert(!conflict.posted,'concurrent location changes block save');assert(conflict.c.lastToast.includes('هم‌زمان'));
 const fail=harness('/settings.html');fail.load('19-phase2-admin.js');fail.c.RAYO_API_GATEWAY.loadModule=async()=>{throw Error('load failed')};await fail.c.p2ReloadPaymentLocations();await fail.c.p2SavePaymentLocations();assert(!fail.posted,'failed load cannot save');assert(fail.c.views.settings().includes('تلاش مجدد'));
 const legacy=harness('/settings.html');legacy.inv.paymentLocations=[{id:'ROOT1',name:'حساب سازگار',isActive:true,custom:'root'}];legacy.load('19-phase2-admin.js');await legacy.c.p2ReloadPaymentLocations();legacy.c.document.querySelectorAll=selector=>selector.startsWith('#p2PaymentLocations')?[{dataset:{paymentLocation:'ROOT1'},querySelector:sel=>sel==='.p2-location-name'?{value:'نام جدید'}:{checked:false}}]:directions.slice(0,2).map(x=>({dataset:{paymentDirection:x.value},querySelector:sel=>sel==='.p2-direction-label'?{value:x.label}:sel==='.p2-direction-effect'?{value:x.effect}:{checked:x.active}}));await legacy.c.p2SavePaymentLocations();assert.equal(legacy.posted.paymentLocations[0].id,'ROOT1');assert.equal(legacy.posted.paymentLocations[0].custom,'root');assert.equal(legacy.posted.paymentLocations[0].isActive,false);assert.equal(legacy.posted.settings.paymentLocations[0].name,'حساب قدیمی','legacy root remains in place without migration');
 console.log('PASS supplier dashboard tab, optional-supplier invoice, blank payment default, embedded payment lists, directions, history, concurrent updates and failed Load');
})().catch(e=>{console.error(e);process.exitCode=1});
