'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const read=f=>fs.readFileSync(f,'utf8');
function harness(){
 const sup={suppliers:[{id:'S1',code:'S1',company:'بهار',status:'فعال'},{id:'S2',code:'S2',company:'تابان',status:'فعال'}],items:[],supplierItems:[{id:'R1',supplierCode:'S1',ingredientId:'I1',itemCode:'101',lastPurchasePriceToman:100,status:'فعال'}],purchaseRequests:[]};
 const pr={ingredients:[{id:'I1',code:'101',name:'سیب',status:'فعال',purchaseUnit:'کیلو',recipeUnit:'گرم',packageQuantity:1000,lastPurchasePriceToman:100},{id:'I2',code:'102',name:'پرتقال',status:'فعال',purchaseUnit:'کیلو',recipeUnit:'گرم',packageQuantity:1000,lastPurchasePriceToman:200}],ingredientPriceHistory:[]};
 const inv={purchaseInvoices:[],supplierPayments:[],stockReceipts:[]},nodes={},writes=[],prompts=[],answers=[],events={};let lineRows=[],fail='';
 const c={console,URL,URLSearchParams,Date,Math,Set,Map,location:{pathname:'/suppliers.html',href:'http://qa/suppliers.html?tab=invoices',search:'?tab=invoices'},history:{replaceState(){}},sessionStorage:{getItem:()=> 'qa'},document:{readyState:'loading',documentElement:{dataset:{}},getElementById:id=>nodes[id]||null,querySelector:()=>null,querySelectorAll:selector=>selector.includes('piLines')?lineRows:[],addEventListener:(name,fn)=>{events[name]=fn}},modalTitle:{},modalBody:{},modalFoot:{},modalBackdrop:{classList:{add(){}}},setTimeout:()=>0,clearTimeout(){},renderView(){},closeModal(){},toast:(s)=>{c.lastToast=s},confirm:s=>{prompts.push(s);return answers.shift()??false},getSupplierState:()=>sup,getPricingState:()=>pr,getInventoryState:()=>inv,supplierUI:{},views:{suppliers:()=>'',cashReport:()=>''},RayoJalali:{today:()=> '1405/06/29'},RayoIngredientMath:{grossCost:i=>i.lastPurchasePriceToman/i.packageQuantity},RayoReorder:{assess:()=>({stock:0,point:10,known:true,need:true})},RayoOpsAnalytics:{currentPosition:()=>({current:0})},supSaveData:async()=>{if(fail==='suppliers')throw Error('save failed');writes.push('suppliers')},RAYO_API_GATEWAY:{saveModule:async(m,data)=>{if(fail===m)throw Error('save failed');writes.push(m)}}};
 c.window=c;vm.createContext(c);vm.runInContext(read('js/42-operations-v10-9-2.js').replace('function install(){','window.testOps={orderRows,orderUI,documentUI,syncInvoicePrices,confirmInvoicePrices,supplierAccount};function install(){'),c);events.DOMContentLoaded();
 function field(id,value){nodes[id]={value:String(value)}}
 function invoice(lines=[['I1',2,150],['I2',1,250]],supplier='',status='finalized'){
  for(const [id,value] of Object.entries({piSupplier:supplier,piNumber:'QA-'+inv.purchaseInvoices.length,piDate:'1405/06/29',piStatus:status,piOrder:'',piDiscount:0,piTax:0,piExtra:0,piNotes:''}))field(id,value);
  lineRows=lines.map(([id,qty,price])=>({querySelector:sel=>({value:({'.pdl-item':id,'.pdl-qty':qty,'.pdl-unit':'کیلو','.pdl-factor':1000,'.pdl-price':price,'.pdl-discount':0})[sel]})}));
 }
 return{c,sup,pr,inv,nodes,writes,prompts,answers,field,invoice,setFail:m=>fail=m};
}
(async()=>{
 let h=harness();assert.equal(h.writes.length,0,'install/load never saves');
 h.c.RayoV1092.newOrder('I2');assert(h.c.modalBody.innerHTML.includes('تابان'),'unlinked item can open an order with active suppliers');
 const beforePricing=JSON.stringify(h.pr),beforeRelation=JSON.stringify(h.sup.supplierItems),beforeInv=JSON.stringify(h.inv);
 for(const [id,v] of Object.entries({v1092OrderSupplier:'S1',v1092OrderQty:2,v1092OrderPrice:999,v1092OrderEta:'1405/06/30'}))h.field(id,v);
 await h.c.RayoV1092.saveOrder('I1');assert.deepStrictEqual(h.writes,['suppliers']);assert.equal(JSON.stringify(h.pr),beforePricing);assert.equal(JSON.stringify(h.sup.supplierItems),beforeRelation);assert.equal(JSON.stringify(h.inv),beforeInv);
 h.sup.purchaseRequests=[{id:'multi',supplierId:'S1',status:'ثبت‌شده',lines:[{ingredientId:'I1'}]}];assert.equal(h.c.testOps.orderRows()[0].request.id,'multi');h.c.testOps.orderUI.supplierId='S2';assert.equal(h.c.testOps.orderRows().length,0);h.c.testOps.orderUI.supplierId='';h.c.testOps.orderUI.search='سيب';assert.equal(h.c.testOps.orderRows().length,1,'Arabic/Persian search normalization');
 h=harness();h.invoice();h.answers.push(true,false);await h.c.RayoV1092.savePurchaseInvoice();assert.equal(h.inv.purchaseInvoices.length,1,'supplier is optional');assert.equal(h.prompts.length,2,'separate prompt per changed item');assert.equal(h.pr.ingredients[0].lastPurchasePriceToman,150);assert.equal(h.pr.ingredients[1].lastPurchasePriceToman,200);assert.equal(h.pr.ingredientPriceHistory.length,1);assert.equal(h.inv.purchaseInvoices[0].lines[1].updateCatalogPrice,false);assert(!h.writes.includes('suppliers'),'invoice does not mutate order workflow');assert.equal(h.c.testOps.supplierAccount(h.inv,'S1').balance,0,'anonymous invoice creates no supplier debt');
 await h.c.RayoV1092.retryInvoicePricing(h.inv.purchaseInvoices[0].id);assert.equal(h.pr.ingredients[1].lastPurchasePriceToman,200,'retry respects rejection');assert.equal(h.pr.ingredientPriceHistory.length,1,'retry is idempotent');
 h=harness();h.invoice(undefined,'S1','draft');await h.c.RayoV1092.savePurchaseInvoice();assert.equal(h.prompts.length,0);assert.deepStrictEqual(h.writes,['inventory']);assert.equal(h.pr.ingredients[0].lastPurchasePriceToman,100);
 h=harness();h.invoice();h.answers.push(true,true);h.setFail('inventory');await h.c.RayoV1092.savePurchaseInvoice();assert.equal(h.inv.purchaseInvoices.length,0);assert.equal(h.pr.ingredients[0].lastPurchasePriceToman,100);
 h=harness();h.invoice();h.answers.push(true,false);h.setFail('pricing');await h.c.RayoV1092.savePurchaseInvoice();assert.equal(h.inv.purchaseInvoices[0].pricingSyncStatus,'failed');assert.equal(h.pr.ingredients[0].lastPurchasePriceToman,100,'failed price save restores memory');h.setFail('');await h.c.RayoV1092.retryInvoicePricing(h.inv.purchaseInvoices[0].id);assert.equal(h.pr.ingredients[0].lastPurchasePriceToman,150);assert.equal(h.pr.ingredients[1].lastPurchasePriceToman,200);
 h=harness();h.invoice();await h.c.RayoV1092.savePurchaseInvoice();assert.equal(h.pr.ingredientPriceHistory.length,0,'all declines preserve price history');assert.equal(h.pr.ingredients[0].lastPurchasePriceToman,100);
 assert(!h.writes.includes('pricing'),'all declines must not save pricing');
 h=harness();h.invoice([['I1',1,150],['I1',1,175]]);h.answers.push(true,true);await h.c.RayoV1092.savePurchaseInvoice();assert.equal(h.pr.ingredients[0].lastPurchasePriceToman,175);assert.equal(h.pr.ingredientPriceHistory[0].priceToman,175,'repeated item uses matching final approved snapshot');
 h=harness();h.invoice([['I1',1,150],['I1',1,175]]);h.answers.push(true,false);await h.c.RayoV1092.savePurchaseInvoice();assert.equal(h.pr.ingredients[0].lastPurchasePriceToman,150,'later declined row cannot overwrite approved price');
 h=harness();h.invoice(undefined,'S1');h.answers.push(true,false);await h.c.RayoV1092.savePurchaseInvoice();const id=h.inv.purchaseInvoices[0].id;h.c.testOps.documentUI.editId=id;h.invoice([['I1',1,190]],'S1');h.answers.push(true);await h.c.RayoV1092.savePurchaseInvoice();assert.equal(h.inv.purchaseInvoices.length,1);assert.equal(h.inv.purchaseInvoices[0].pricingSyncStatus,'synced','edited invoice stores final sync state');assert.equal(h.pr.ingredients[0].lastPurchasePriceToman,190);
 h=harness();h.invoice([['I1',1,0]],'S1');await h.c.RayoV1092.savePurchaseInvoice();assert.equal(h.writes.length,0,'invalid final price cannot be saved');
 // Exercise the final relation renderer and picker with stable input nodes.
 h=harness();const listeners={},inputs={};let renders=0;h.c.renderView=()=>renders++;h.c.pageHead=()=>'';h.c.document.querySelector=()=>({});h.c.document.addEventListener=(name,fn)=>{(listeners[name]??=[]).push(fn)};h.c.document.dispatchEvent=e=>{for(const f of listeners[e.type]||[])f(e)};h.c.CustomEvent=function(type,init){this.type=type;this.detail=init.detail};
 for(const key of ['relationSupplier','relationItem']){inputs[key]={value:'',setAttribute(){}};h.nodes[key+'Search']=inputs[key];h.nodes[key]={value:''};h.nodes[key+'List']={innerHTML:'',hidden:true};}h.nodes.supplierRelationResults={innerHTML:''};
 vm.runInContext(read('js/43-central-catalog-v10-10.js').replace('function install(){','window.testCatalog={relationsView,filterRelations};function install(){'),h.c);for(const f of listeners.DOMContentLoaded||[])f();renders=0;
 const html=h.c.testCatalog.relationsView();assert(html.includes("onfocus=\"RayoSearchPicker.filter('relationSupplier','')\""));
 for(const q of ['ب','به','بها','بهار']){inputs.relationSupplier.value=q;h.c.testCatalog.filterRelations('relationSupplier',q);assert.strictEqual(h.nodes.relationSupplierSearch,inputs.relationSupplier);assert(h.nodes.supplierRelationResults.innerHTML.includes('سیب'));}assert.equal(renders,0,'typing never replaces focused form');
 h.c.RayoSearchPicker.pick('relationSupplier','S1');assert.equal(h.c.supplierUI.relationSupplier,'S1');assert.equal(h.c.supplierUI.relationSupplierSearch,'');
 h.c.testCatalog.filterRelations('relationItem','پرتقال');assert(h.nodes.supplierRelationResults.innerHTML.includes('پیدا نشد'));h.c.testCatalog.filterRelations('relationItem','سيب');assert(h.nodes.supplierRelationResults.innerHTML.includes('سیب'));h.c.RayoSearchPicker.pick('relationItem','I1');assert.equal(h.c.supplierUI.relationItem,'I1');
 assert(read('js/46-inventory-operations-v10-12.js').includes("['invoices','فاکتورهای خرید']"));assert(read('js/40-rayo-v10-9-comprehensive.js').includes("'کارت تنخواه'"));assert(read('js/04-rayo-suppliers-admin-module.js').includes('tab=payment&supplier=${encodeURIComponent(s.id)}'));
 console.log('PASS supplier workflows: independent orders, filters, optional supplier, per-line price approval, drafts, save failures and retry');
})().catch(e=>{console.error(e);process.exitCode=1});
