const fs=require('fs'),path=require('path'),vm=require('vm'),{webcrypto}=require('crypto');
const root=__dirname,config=fs.readFileSync(path.join(root,'js/config.js'),'utf8'),base=fs.readFileSync(path.join(root,'js/00-base.js'),'utf8'),closeout=fs.readFileSync(path.join(root,'js/35-operational-closeout-v10-2.js'),'utf8'),calls=[];
let responders=[],uuidNo=0;
function response(status,body){return{ok:status>=200&&status<300,status,async text(){return body===undefined?'':JSON.stringify(body)}}}
const sandbox={window:{RAYO_ENV:{API_ORIGIN:'https://test.local',API_PREFIX:'/api/v1.0',API_CONTROLLER:'/RayoData',TIMEOUT_MS:100}},location:{pathname:'/personnel.html'},document:{getElementById(){return null}},fetch:async(url,options={})=>{calls.push({url,options});const fn=responders.shift();if(!fn)throw Error('unexpected fetch '+url);return fn(url,options)},AbortController,Uint8Array,crypto:{...webcrypto,randomUUID:()=>`00000000-0000-4000-8000-${String(++uuidNo).padStart(12,'0')}`},setTimeout,clearTimeout,console,Date,Math,JSON,Object,Array,Map,Set,WeakSet,Error,String,Number,Boolean,Promise,encodeURIComponent};
sandbox.window.window=sandbox.window;sandbox.globalThis=sandbox;vm.createContext(sandbox);new vm.Script(config).runInContext(sandbox);
const gateway=sandbox.window.RAYO_API_GATEWAY,checks=[];function ok(name,value){if(!value)throw Error('FAIL: '+name);checks.push(name)}async function rejects(name,fn,test){let e;try{await fn()}catch(x){e=x}ok(name,e&&test(e))}
const tip1={id:'TIPG-140506-0001',receiveDate:'1405/06/01',type:'فردی',status:'ثبت‌شده',totalAmount:1000,settledAmount:0,participants:[{personnelId:'EMP-001',weight:1}]};
const tip2={id:'TIPG-140506-0002',receiveDate:'1405/06/02',type:'کلی',status:'تسویه‌شده',totalAmount:3000,settledAmount:3000,participants:[{personnelId:'EMP-001',weight:1},{personnelId:'EMP-002',weight:2}]};
const personnelFixture=[{id:'EMP-KITCHEN',name:'آشپز فعال',status:'فعال',section:'آشپزخانه',mainPosition:'آشپز',personnelGroup:'آشپزخانه'},{id:'EMP-HALL',name:'سالن فعال',status:'فعال',section:'سالن بالا',mainPosition:'ویتر',personnelGroup:'سالن'},{id:'EMP-BAR',name:'بار فعال',status:'فعال',section:'بار',mainPosition:'باریستا',personnelGroup:'سالن'},{id:'EMP-OTHER',name:'خدمات فعال',status:'فعال',section:'خدمات',mainPosition:'خدماتی',personnelGroup:'خدمات'},{id:'EMP-INACTIVE',name:'غیرفعال',status:'اتمام همکاری',section:'آشپزخانه',mainPosition:'آشپز',personnelGroup:'آشپزخانه'}];
const group3={id:'TIPG-3',receiveDate:'1405/06/03',type:'کلی',status:'ثبت‌شده',totalAmount:6000,settledAmount:0,participants:[{personnelId:'EMP-KITCHEN',weight:1},{personnelId:'EMP-HALL',weight:2},{personnelId:'EMP-BAR',weight:3}]};

(async()=>{
  responders.push(()=>response(200,{items:[tip1],page:1,pageSize:1,total:2,totalPages:2,version:4}),()=>response(200,{items:[tip2],page:2,pageSize:1,total:2,totalPages:2,version:4}));
  const first=await gateway.queryCollection({module:'personnel',collection:'tipGroups',filters:{},dateField:'receiveDate',sortBy:'receiveDate',descending:true,page:1,pageSize:1});
  const second=await gateway.queryCollection({module:'personnel',collection:'tipGroups',filters:{},dateField:'receiveDate',sortBy:'receiveDate',descending:true,page:2,pageSize:1});
  const all=[...first.items,...second.items];ok('نمایش انعام بدون فیلتر',all.length===2&&calls.every(x=>!x.url.includes('/Load')));
  responders.push(()=>response(200,{items:[tip1,tip2],page:1,pageSize:500,total:2,totalPages:1,version:4}));
  await gateway.queryCollection({module:'personnel',collection:'tipGroups',filters:{},pageSize:500});
  const personBody=JSON.parse(calls.at(-1).options.body);ok('فیلتر عضویت جعلی به Backend ارسال نمی‌شود',!Object.keys(personBody.filters).some(x=>x.includes('participants')));
  const share=g=>{const ps=g.participants,w=ps.reduce((s,x)=>s+x.weight,0),p=ps.find(x=>x.personnelId==='EMP-001');return p?g.totalAmount*p.weight/w:0};ok('محاسبه جمع انعام فیلترشده',Math.abs(all.reduce((s,g)=>s+share(g),0)-2000)<0.01);
  const active=personnelFixture.filter(x=>x.status==='فعال');ok('همه بخش‌های فعال در فرم انعام',active.some(x=>x.id==='EMP-KITCHEN')&&active.some(x=>x.id==='EMP-HALL')&&active.some(x=>x.id==='EMP-BAR')&&active.some(x=>x.id==='EMP-OTHER')&&!active.some(x=>x.id==='EMP-INACTIVE')&&base.includes('function tipEligibleV5(){return [...activePersonnel()]')&&base.includes("RAYO_API_GATEWAY.loadModule('hr')"));
  const shares=g=>{const totalWeight=g.participants.reduce((s,x)=>s+x.weight,0);return g.participants.map(x=>({...x,amount:g.totalAmount*x.weight/totalWeight}))},before=JSON.stringify(group3),full=shares(group3),selected=full.filter(x=>x.personnelId==='EMP-HALL');ok('نمایش کامل رکورد سه‌نفره بدون فیلتر',full.length===3);ok('Projection فقط نفر انتخاب‌شده',selected.length===1&&selected[0].personnelId==='EMP-HALL'&&selected[0].amount===2000&&base.includes('function tipRowProjection(g,personnelId=ui.tipFilter.personnelId)'));ok('Projection داده اصلی را تغییر نمی‌دهد',JSON.stringify(group3)===before&&base.includes('return{record:g,shares:visibleShares'));
  ok('ویرایش از رکورد کامل اصلی استفاده می‌کند',base.includes("const g=id?state.tipGroups.find(x=>x.id===id)")&&base.includes("onclick=\"editTip('${esc(g.id)}')\""));
  responders.push(()=>response(200,{items:[tip1],page:1,pageSize:500,total:1,totalPages:1,version:4}));
  await gateway.queryCollection({module:'personnel',collection:'tipGroups',dateField:'receiveDate',from:'1405-06-01',to:'1405-06-30',pageSize:500});
  const dateBody=JSON.parse(calls.at(-1).options.body);ok('فیلتر بازه تاریخ',dateBody.dateField==='receiveDate'&&dateBody.from==='1405-06-01'&&dateBody.to==='1405-06-30');
  for(const operation of ['insert','update','archive']){responders.push(()=>response(200,{ok:true,version:gateway.getModuleVersion('personnel')+1}));await gateway.mutateRecord({module:'personnel',collection:'tipGroups',operation,recordId:operation==='insert'?'TIPG-NEW':'TIPG-140506-0001',idField:'id',requestId:`req-${operation}`,data:operation==='archive'?{isArchived:true}:tip1});const body=JSON.parse(calls.at(-1).options.body);ok(`${operation==='insert'?'ثبت رکورد جدید':operation==='update'?'ویرایش رکورد':'Archive رکورد'}`,body.operation===operation&&body.idField==='id'&&body.collection==='tipGroups')}
  responders.push(()=>response(200,{ok:true,version:gateway.getModuleVersion('personnel')+1}));await gateway.mutateRecord({module:'personnel',collection:'tipGroups',operation:'insert',recordId:group3.id,idField:'id',requestId:'req-kitchen',data:group3});let fixtureBody=JSON.parse(calls.at(-1).options.body);ok('ثبت انعام برای پرسنل آشپزخانه',fixtureBody.data.participants.some(x=>x.personnelId==='EMP-KITCHEN'));
  responders.push(()=>response(200,{ok:true,version:gateway.getModuleVersion('personnel')+1}));await gateway.mutateRecord({module:'personnel',collection:'tipGroups',operation:'update',recordId:group3.id,idField:'id',requestId:'req-edit-full',data:group3});fixtureBody=JSON.parse(calls.at(-1).options.body);ok('ویرایش فیلترشده اعضای پنهان را حذف نمی‌کند',fixtureBody.data.participants.length===3);
  const before409=calls.length;responders.push(()=>response(409,{code:'version_conflict',message:'stale'}));await rejects('خطای 409',()=>gateway.mutateRecord({module:'personnel',collection:'tipGroups',operation:'update',recordId:tip1.id,requestId:'conflict-once',data:tip1}),e=>e.status===409&&e.code==='version_conflict'&&calls.length===before409+1);
  responders.push(()=>{throw new TypeError('Failed to fetch')});await rejects('قطع شبکه',()=>gateway.queryCollection({module:'personnel',collection:'tipGroups',filters:{status:'شبکه'},pageSize:500}),e=>e.code==='network_error'&&gateway.getModuleStatus('personnel').readOnly===true);
  ok('دوبار کلیک روی ثبت',base.includes('if(tipGatewayState.submitting||tipGatewayState.loading||tipGatewayState.error)return')&&base.includes('pending.fingerprint!==fingerprint')&&base.includes('requestId:pending.requestId'));
  ok('تلاش تازه پس از خطا requestId تازه دارد',base.includes('pending.requestId=RAYO_API_GATEWAY.createRequestId()')&&base.includes('pendingArchives.set(id,RAYO_API_GATEWAY.createRequestId())'));
  ok('رفت‌وبرگشت بدون Query غیرضروری',base.includes('tipGatewayState.cache.get(key)')&&base.includes('tipGatewayState.cache.has(tipQueryKey())'));
  ok('تمام صفحات Query برای جمع دقیق',base.includes('page<=first.totalPages')&&base.includes('items.push(...next.items)'));
  ok('عدم Save شدن DEFAULT_DATA',base.includes("!tipsOnlyPage()")&&!/tipsOnlyPage\(\)[\s\S]{0,500}StorageAdapter\.save/.test(base)&&!base.slice(base.indexOf("TIP_QUERY_COLLECTION='tipGroups'"),base.indexOf('const views=')).includes('saveModule('));
  ok('عدم Load کامل جانبی در نمای انعام',closeout.includes("if(!(file==='personnel.html'&&view==='tips'))ensureEmploymentStatus()"));
  ok('Load Save سایر personnel بدون تغییر مسیر',base.includes("return window.RAYO_API_GATEWAY.loadOrBootstrap('hr')")&&base.includes("saveModule('hr',data"));
  ok('Query Mutate انعام فقط در فایل مالک آن است',!fs.readdirSync(path.join(root,'js')).filter(x=>!['00-base.js','config.js','11-rayo-cash-report-module.js'].includes(x)).some(f=>f.endsWith('.js')&&/queryCollection\(|mutateRecord\(/.test(fs.readFileSync(path.join(root,'js',f),'utf8'))));
  console.log(`PASS ${checks.length}`);checks.forEach(x=>console.log('  ✓ '+x));
})().catch(e=>{console.error(e);process.exitCode=1});
