'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert'),{webcrypto}=require('crypto');
const read=f=>fs.readFileSync(f,'utf8'),copy=x=>JSON.parse(JSON.stringify(x));
function fixture(){
 const item={id:'flour',code:'QA-F',name:'آرد آزمایشی',recipeUnit:'کیلوگرم',purchaseUnit:'کیلوگرم',packageQuantity:1,lastPurchasePriceToman:10,status:'فعال',wastePercent:0,reorderPoint:90};
 const pricing={meta:{initialized:true},ingredients:[item,{...item,id:'uncounted',code:'QA-U',name:'قلم شمارش نشده'}],settings:{},lists:{},menuItems:[{id:'food',name:'غذای آزمایشی',currentPriceToman:100,productionLocationId:'kitchen'},{id:'drink',name:'بار آزمایشی',currentPriceToman:100,productionLocationId:'bar'}],recipes:[{menuItemId:'food',ingredientId:'flour',quantity:1},{menuItemId:'drink',ingredientId:'flour',quantity:1}],recipeVersions:[{id:'rv-food',menuItemId:'food',effectiveFrom:'1405/05/01',lines:[{ingredientId:'flour',quantity:1,recipeUnit:'کیلوگرم',wastePercent:0}]},{id:'rv-drink',menuItemId:'drink',effectiveFrom:'1405/05/01',lines:[{ingredientId:'flour',quantity:1,recipeUnit:'کیلوگرم',wastePercent:0}]}],ingredientPriceHistory:[],changeLog:[]};
 const inventory={meta:{initialized:true},settings:{mainLocationId:'main',defaultSalesLocationId:'kitchen'},locations:[{id:'main',name:'انبار اصلی',isActive:true},{id:'kitchen',name:'آشپزخانه',isActive:true},{id:'bar',name:'بار',isActive:true}],openingBalances:[],stocktakes:[{id:'opening-september',date:'1405/06/01',locationId:'main',status:'approved',isOpeningBaseline:true,lines:[{ingredientId:'flour',actual:100,unitSnapshot:'کیلوگرم',unitCost:10}],createdAt:'2026-09-01T00:00:00Z',unknownOpening:{preserve:true}}],stockReceipts:[{id:'receipt-20',date:'1405/06/01',locationId:'bar',ingredientId:'flour',quantity:20,purchaseQuantity:20,unitPrice:10,status:'received',invoiceId:'invoice-20',unitSnapshot:'کیلوگرم'}],purchaseInvoices:[{id:'invoice-20',date:'1405/06/01',status:'posted',lines:[{ingredientId:'flour',quantity:20,unitPrice:10}]}],inventoryMovements:[],salesPeriods:[{id:'sale-30',from:'1405/06/01',to:'1405/06/01',status:'posted',lines:[{menuItemId:'food',quantity:30}]}],wasteRecords:[{id:'waste-2',date:'1405/06/01',type:'ingredient',itemId:'flour',quantity:2,eventType:'WASTE',locationId:'kitchen',reviewStatus:'تأییدشده'}],consumptionRecords:[{id:'staff-3',recordKind:'consumption',date:'1405/06/01',type:'ingredient',itemId:'flour',quantity:3,eventType:'STAFF_CONSUMPTION',locationId:'bar'}],periodClosures:[],changeLog:[],unknownRoot:{preserve:['nested',1]}};
 return {inventory,pricing,suppliers:{meta:{initialized:true},suppliers:[],items:[],supplierItems:[]},personnel:{meta:{initialized:true},personnel:[]},cashreport:{meta:{initialized:true},reports:[]}};
}
async function setup({failLoad=false,dropField=false}={}){
 const server=fixture(),calls=[],messages=[],elements={},countInputs=[],downloads=[];let inventory,pricing,failSave=false;
 const el=id=>elements[id]||(elements[id]={value:'',checked:false,textContent:'',innerHTML:'',style:{},dataset:{},addEventListener(){},classList:{add(){},remove(){}}});
 const c={console,URL,URLSearchParams,Blob,AbortController,Uint8Array,crypto:webcrypto,location:{pathname:'/qa.html',search:''},currentView:'qa',setTimeout:(fn,ms)=>ms>=400&&ms<=3000?setTimeout(fn,0):0,clearTimeout,sessionStorage:{getItem:()=> 'qa-manager'},RAYO_ENV:{API_ORIGIN:'https://fixture.invalid',TIMEOUT_MS:200},
 document:{readyState:'loading',documentElement:{dataset:{}},getElementById:el,querySelector:()=>null,querySelectorAll:s=>s==='[data-whole-count]'?countInputs:[],createElement:()=>({click(){downloads.push(true)},remove(){}}),body:{appendChild(){}},head:{appendChild(){}},addEventListener(){}},$:el,esc:x=>String(x??''),toast:m=>messages.push(m),renderView(){},closeModal(){},confirm:()=>true,RayoJalali:{today:()=> '1405/06/03'},getInventoryState:()=>inventory,getSupplierState:()=>server.suppliers,getCashReportState:()=>server.cashreport,
 fetch:async(url,options={})=>{calls.push({url,method:options.method||'GET'});const u=new URL(url),module=u.searchParams.get('module');if(failLoad||failSave&&options.method==='POST')return {ok:false,status:503,text:async()=>JSON.stringify({message:'fixture unavailable'})};if(u.pathname.endsWith('/Save')){server[module]=JSON.parse(options.body);if(dropField)delete server[module].settings.inventoryControlMode;return {ok:true,status:200,text:async()=>JSON.stringify({ok:true})}}if(!u.pathname.endsWith('/Load')||!server[module])throw Error('Unexpected test request '+url);return {ok:true,status:200,text:async()=>JSON.stringify(server[module])}}
 };c.window=c;vm.createContext(c);vm.runInContext(read('js/config.js'),c);
 const pricingCode=read('js/08-rayo-pricing-admin-module.js').replace('(function waitPricingModule(){','window.pcEnsureLoaded=pcEnsureLoaded;window.getPricingState=()=>pricingState;(function waitPricingModule(){');vm.runInContext(pricingCode,c);
 if(!failLoad){inventory=await c.RAYO_API_GATEWAY.loadModule('inventory');await c.pcEnsureLoaded();pricing=c.getPricingState()}
 vm.runInContext(read('js/32-inventory-cost-control-v10.js'),c);const api=c.RayoInventoryV10;await api.ensure();
 return {c,api,server,calls,messages,inventory,pricing,el,countInputs,downloads,failSave:v=>failSave=v};
}
async function convert(t){t.el('rayoControlMode').value='unified';t.el('rayoControlOpening').value='stocktake:opening-september';t.el('rayoControlBoundary').value='START';await t.api.previewControlChange();t.api.downloadControlBackup();t.el('rayoControlConfirm').checked=true;await t.api.applyControlChange();assert.equal(t.inventory.settings.inventoryControlMode,'unified',t.messages.join('\n'))}
async function count(t,values,date='1405/06/02'){t.el('rayoWholeDate').value=date;t.el('rayoWholeKind').value='END';t.countInputs.splice(0,t.countInputs.length,...Object.entries(values).map(([id,value])=>({dataset:{wholeCount:id},value:String(value)})));await t.api.saveUnifiedCount()}
async function run(){let groups=0;const test=async(name,fn)=>{await fn();groups++;console.log('PASS '+name)};
 await test('real Gateway: read-only Load, explicit backed-up conversion, preserved unknown fields and Save/Load',async()=>{const t=await setup();assert(!t.calls.some(c=>c.method==='POST'));assert(!t.calls.some(c=>c.url.includes('seed')));const original=copy(t.server.inventory.stocktakes[0]);await convert(t);assert.equal(t.downloads.length,1);const saved=t.server.inventory.stocktakes[0];assert.equal(saved.locationId,'main');assert.deepEqual(saved.lines,original.lines);assert.deepEqual(saved.unknownOpening,original.unknownOpening);assert.deepEqual(t.server.inventory.unknownRoot,{preserve:['nested',1]});assert.equal(t.inventory.settings.inventoryControlMode,'unified');assert.equal(t.api.currentTotalPosition('flour','1405/06/01').quantity,85);assert.equal(t.api.currentTotalPosition('uncounted').quantity,null);const fresh=await t.c.RAYO_API_GATEWAY.loadModule('inventory');assert.equal(fresh.stocktakes[0].baselineBoundary,'START');assert.equal(fresh.settings.inventoryControlMode,'unified')});
 await test('100 + 20 - 30 - 2 - 3 = 85; 83 count gives -2; next baseline 83, no duplicate adjustment',async()=>{const t=await setup();await convert(t);await count(t,{flour:83,uncounted:0});const st=t.inventory.stocktakes.at(-1);assert.equal(st.inventoryScope,'RAYO',t.messages.join('\n'));assert.equal(st.lines[0].expected,85);assert.equal(st.lines[0].variance,-2);assert.equal(t.api.currentTotalPosition('flour','1405/06/03').quantity,83);t.inventory.inventoryMovements.push({id:'adjust',movementType:'ADJUSTMENT',ingredientId:'flour',quantityDelta:-2,date:'1405/06/03',referenceType:'stocktake',referenceId:st.id,locationId:'main',status:'posted'});assert.equal(t.api.currentTotalPosition('flour').quantity,83);assert.equal(t.api.currentTotalPosition('uncounted').quantity,0);const before=t.calls.length;await count(t,{flour:70});assert.equal(t.calls.filter(c=>c.method==='POST').length,2,'same/later date duplicate count blocked');assert(t.calls.length>=before)});
 await test('late transfer create/edit/void and inactive locations have zero whole effect',async()=>{const t=await setup();await convert(t);const m={id:'transfer',ingredientId:'flour',movementType:'TRANSFER',date:'1405/06/01',quantity:10,fromLocationId:'main',toLocationId:'kitchen',status:'posted'};t.inventory.inventoryMovements.push(m);for(const q of [10,15]){m.quantity=q;assert.equal(t.api.currentTotalPosition('flour').quantity,85)}m.status='void';assert.equal(t.api.currentTotalPosition('flour').quantity,85);t.inventory.locations.find(l=>l.id==='bar').isActive=false;assert.equal(t.api.currentTotalPosition('flour').quantity,85)});
 await test('multiple sections, dated recipes, signed sales returns, void sales and waste exactly once',async()=>{const t=await setup();await convert(t);t.inventory.salesPeriods.push({id:'bar-sales',date:'1405/06/02',lines:[{menuItemId:'drink',quantity:5}]});assert.equal(t.api.currentTotalPosition('flour').quantity,80);t.inventory.salesPeriods.at(-1).status='void';assert.equal(t.api.currentTotalPosition('flour').quantity,85);t.inventory.salesPeriods.push({date:'1405/06/02',lines:[{menuItemId:'food',quantity:-2}]});assert.equal(t.api.currentTotalPosition('flour').quantity,87);t.inventory.wasteRecords[0].status='void';assert.equal(t.api.currentTotalPosition('flour').quantity,89);t.pricing.recipeVersions.push({id:'new',menuItemId:'food',effectiveFrom:'1405/06/03',lines:[{ingredientId:'flour',quantity:2,recipeUnit:'کیلوگرم',wastePercent:0}]});t.inventory.salesPeriods.push({date:'1405/06/03',lines:[{menuItemId:'food',quantity:1}]});assert.equal(t.api.currentTotalPosition('flour').quantity,87)});
 await test('section count cannot reset whole; incomplete coverage is unknown; opening day and closed snapshots',async()=>{const t=await setup();await convert(t);t.inventory.stocktakes.push({id:'section',date:'1405/06/02',locationId:'kitchen',status:'approved',lines:[{ingredientId:'flour',actual:999}]});assert.equal(t.api.currentTotalPosition('flour').quantity,85);await count(t,{flour:83});const m=t.api.periodMetrics('1405/06/01','1405/06/02');assert.equal(m.scope,'RAYO');assert.equal(m.lines.find(l=>l.ingredientId==='flour').variance,-2);assert.equal(m.coverage,50);assert.equal(m.unexplained,null);assert.equal(t.api.currentTotalPosition('uncounted').quantity,null);t.inventory.periodClosures.push({id:'closed',status:'closed',from:'1405/06/01',to:'1405/06/02',metrics:{sales:500,unexplained:123,openingValue:100,purchases:20},lines:[]});assert.equal(t.api.periodMetrics('1405/06/01','1405/06/02').unexplained,123)});
 await test('missing recipe/menu, unit mismatch, aggregated boundary ambiguity, negatives remain visible',async()=>{const t=await setup();await convert(t);t.inventory.salesPeriods[0].lines[0].menuItemId='missing';let p=t.api.currentTotalPosition('flour');assert.equal(p.quantity,null);assert(p.issues.some(s=>s.includes('اتصال')));t.inventory.salesPeriods[0].lines[0].menuItemId='food';t.pricing.recipeVersions[0].lines[0].recipeUnit='لیتر';assert.equal(t.api.currentTotalPosition('flour').quantity,null);t.pricing.recipeVersions[0].lines[0].recipeUnit='کیلوگرم';t.inventory.salesPeriods[0].lines[0].quantity=200;assert.equal(t.api.currentTotalPosition('flour').quantity,-85);t.inventory.salesPeriods[0].from='1405/05/31';assert.equal(t.api.currentTotalPosition('flour').quantity,null)});
 await test('overlap and closed-period conversion blocked; Backup and manager confirmation required',async()=>{const t=await setup();t.server.inventory.openingBalances.push({id:'overlap',ingredientId:'flour',locationId:'bar',date:'1405/06/01',quantity:10});t.el('rayoControlMode').value='unified';t.el('rayoControlOpening').value='stocktake:opening-september';t.el('rayoControlBoundary').value='START';await t.api.previewControlChange();t.el('rayoControlConfirm').checked=true;await t.api.applyControlChange();assert(!t.calls.some(c=>c.method==='POST'));assert(t.messages.some(m=>m.includes('هم‌پوشان')));t.server.inventory.openingBalances=[];t.server.inventory.periodClosures=[{status:'closed',from:'1405/06/01',to:'1405/06/31'}];await t.api.previewControlChange();assert(t.messages.some(m=>m.includes('دوره بسته')))});
 await test('rollback restores metadata without deleting original records; server drift blocks stale preview',async()=>{const t=await setup();await convert(t);await t.api.previewControlRollback();t.api.downloadControlBackup();await t.api.applyControlChange();assert.equal(t.inventory.settings.inventoryControlMode,undefined);assert.equal(t.inventory.stocktakes[0].inventoryScope,undefined);assert.equal(t.inventory.stocktakes[0].lines[0].actual,100);t.el('rayoControlOpening').value='';await t.api.previewControlChange();t.api.downloadControlBackup();t.server.inventory.unknownRoot.concurrent='keep';await t.api.applyControlChange();assert(t.messages.some(m=>m.includes('سرور تغییر')));assert.equal(t.server.inventory.unknownRoot.concurrent,'keep')});
 await test('failed Load never seeds/saves; DTO field loss is detected without automatic retry',async()=>{const broken=await setup({failLoad:true});assert(!broken.calls.some(c=>c.method==='POST'));assert(!broken.api.isReady());const t=await setup({dropField:true});t.el('rayoControlMode').value='unified';t.el('rayoControlBoundary').value='START';await t.api.previewControlChange();t.api.downloadControlBackup();t.el('rayoControlConfirm').checked=true;await t.api.applyControlChange();assert(t.messages.some(m=>m.includes('یکسان نیست')));await t.api.applyControlChange();assert.equal(t.calls.filter(c=>c.method==='POST').length,1)});
 await test('same-day start/end, successive counts accumulate only inside their report period',async()=>{const t=await setup();await convert(t);await count(t,{flour:84},'1405/06/01');assert.equal(t.inventory.stocktakes.at(-1).lines[0].variance,-1);assert.equal(t.inventory.stocktakes.at(-1).locationId,'','whole scope never becomes a location during normalization');await count(t,{flour:83},'1405/06/02');const line=t.api.periodMetrics('1405/06/01','1405/06/02').lines.find(l=>l.ingredientId==='flour');assert.equal(line.variance,-2);assert.equal(t.api.periodMetrics('1405/06/02','1405/06/02').lines.find(l=>l.ingredientId==='flour').variance,-1);assert.equal(t.api.currentTotalPosition('flour').quantity,83)});
 await test('openingBalances conversion, end-day boundary and pending/archived document contracts',async()=>{const t=await setup();t.server.inventory.openingBalances=[{id:'open-row',date:'1405/06/01',locationId:'main',ingredientId:'flour',quantity:100}];t.server.inventory.stocktakes=[];t.el('rayoControlMode').value='unified';t.el('rayoControlOpening').value='opening:1405/06/01:main';t.el('rayoControlBoundary').value='END';await t.api.previewControlChange();t.api.downloadControlBackup();t.el('rayoControlConfirm').checked=true;await t.api.applyControlChange();assert.equal(t.api.currentTotalPosition('flour').quantity,100,'end-day opening excludes that day exactly once');t.inventory.openingBalances[0].baselineBoundary='START';assert.equal(t.api.currentTotalPosition('flour').quantity,85);t.inventory.inventoryMovements.find(m=>m.movementType==='STAFF_CONSUMPTION').status='pending';assert.equal(t.api.currentTotalPosition('flour').quantity,88);t.inventory.stockReceipts[0].status='pending';assert.equal(t.api.currentTotalPosition('flour').quantity,68);t.inventory.salesPeriods[0].isArchived=true;assert.equal(t.api.currentTotalPosition('flour').quantity,98);t.inventory.wasteRecords[0].reportedByPersonnelId='qa';t.inventory.wasteRecords[0].reviewStatus='در انتظار بررسی';assert.equal(t.api.currentTotalPosition('flour').quantity,100)});
 await test('quantity conservation with adjustments and external return direction; invoice receipt is counted once',async()=>{const t=await setup();await convert(t);t.inventory.inventoryMovements.push({id:'return',ingredientId:'flour',date:'1405/06/02',movementType:'PURCHASE_RECEIPT',quantity:2,fromLocationId:'main',toLocationId:'',unitCostToman:10,status:'posted'},{id:'correction',ingredientId:'flour',date:'1405/06/02',movementType:'ADJUSTMENT',quantityDelta:1,locationId:'main',status:'posted'});assert.equal(t.api.currentTotalPosition('flour').quantity,84);t.inventory.inventoryMovements.at(-1).status='void';assert.equal(t.api.currentTotalPosition('flour').quantity,83);t.inventory.purchaseInvoices[0].status='void';assert.equal(t.api.currentTotalPosition('flour').quantity,63)});
 await test('nine-tab UI uses common results and scope, count form, errors, details and order warnings',async()=>{const t=await setup();await convert(t);const c=t.c;c.location={pathname:'/inventory.html',search:'?tab=stock'};c.views={inventory:()=>''};c.ops={};c.pageHead=(title,sub)=>`<h1>${title}</h1><p>${sub}</p>`;c.document.readyState='complete';vm.runInContext(read('js/40-rayo-v10-9-comprehensive.js').slice(0,read('js/40-rayo-v10-9-comprehensive.js').indexOf('function supplierLedger'))+'})();',c);vm.runInContext(read('js/46-inventory-operations-v10-12.js'),c);await Promise.resolve();let html=c.views.inventory();assert(html.includes('کل رایو'));assert(html.includes('۸۵'));assert(html.includes('این قلم در آخرین مبنای کل شمارش نشده است'));assert.equal((html.match(/class="v1012-tabs"/g)||[]).length,1);c.location.search='?tab=count';html=c.views.inventory();assert(html.includes('data-whole-count'));assert(html.includes('شمارش مستقل محل‌ها'));c.location.search='?tab=settings';html=c.views.inventory();assert(html.includes('rayoControlMode'));assert(html.includes('پیش‌نمایش'));c.location.search='?tab=reorder';html=c.views.inventory();assert(html.includes('آرد آزمایشی'));c.RayoInventoryV1012.itemDetail('flour');assert(t.el('modalBody').innerHTML.includes('opening-september'));assert(t.el('modalBody').innerHTML.includes('۸۵'));assert(t.api.unifiedCountPane().includes('خانه خالی'));for(const path of ['reports.html','suppliers.html','personnel.html'])assert(read(path).includes('32-inventory-cost-control-v10.js'));assert(t.calls.filter(x=>x.method==='POST').length===1,'rendering must not save')});
 await test('operational forecast uses whole stock once, sums defined future profiles and never deducts usage twice',async()=>{const t=await setup();await convert(t);const c=t.c,base=read('js/00-base.js');vm.runInContext(base.slice(base.indexOf('function jdiv('),base.indexOf('function toJalaali('))+base.match(/function jMonthLength[^\n]+/)[0],c);const i=t.pricing.ingredients.find(x=>x.id==='uncounted');i.itemType='OPERATIONAL_CONSUMABLE';t.inventory.stocktakes[0].lines.push({ingredientId:i.id,actual:30,unitSnapshot:i.recipeUnit});t.inventory.operationalConsumptionProfiles=[{id:'p1',ingredientId:i.id,locationId:'main',active:true,unit:i.recipeUnit,fixedQuantity:1,fixedDays:1,effectiveFrom:'1405/06/01'},{id:'p2',ingredientId:i.id,locationId:'bar',active:true,unit:i.recipeUnit,fixedQuantity:2,fixedDays:1,effectiveFrom:'1405/06/01'}];vm.runInContext(read('js/40-rayo-v10-9-comprehensive.js').slice(0,read('js/40-rayo-v10-9-comprehensive.js').indexOf('function supplierLedger'))+'})();',c);vm.runInContext(read('js/46-inventory-operations-v10-12.js'),c);let rows=c.RayoInventoryV1012.unifiedForecastRows();assert.equal(rows.length,1);assert.equal(rows[0].stock,30);assert.equal(rows[0].daily,3);assert.equal(rows[0].future,90);assert.equal(rows[0].buyQty,150);t.inventory.inventoryMovements.push({id:'usage',ingredientId:i.id,date:'1405/06/02',movementType:'OTHER_AUTHORIZED',fromLocationId:'bar',quantity:3,status:'posted'});rows=c.RayoInventoryV1012.unifiedForecastRows();assert.equal(rows[0].stock,27);assert.equal(t.api.currentTotalPosition(i.id).quantity,27);assert.equal(t.calls.filter(x=>x.method==='POST').length,1)});
 console.log(`PASS ${groups} unified inventory acceptance groups`);
}
module.exports={fixture,setup,convert,count};if(require.main===module)run().catch(e=>{console.error(e);process.exitCode=1});
