#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),{spawnSync}=require('child_process');
const root=__dirname,read=f=>fs.readFileSync(path.join(root,f),'utf8'),pass=[],fail=[];
const check=(name,ok,detail='')=>(ok?pass:fail).push(`${name}${detail?' — '+detail:''}`);
for(const f of fs.readdirSync(path.join(root,'js')).filter(x=>x.endsWith('.js')).sort()){const r=spawnSync(process.execPath,['--check',path.join(root,'js',f)],{encoding:'utf8'});check(`JS syntax: ${f}`,r.status===0,(r.stderr||'').trim())}
for(const f of [...fs.readdirSync(path.join(root,'seed')).filter(x=>x.endsWith('.json')).map(x=>'seed/'+x),'RAYO_DATA_MODEL_v10_8_0.json']){try{JSON.parse(read(f));check(`JSON parse: ${f}`,true)}catch(e){check(`JSON parse: ${f}`,false,e.message)}}
let refs=0;const missing=[];for(const f of fs.readdirSync(root).filter(x=>x.endsWith('.html'))){const h=read(f);for(const m of h.matchAll(/(?:src|href)=["']([^"']+)["']/g)){const x=m[1].split(/[?#]/)[0];if(!x||/^(?:https?:|data:|mailto:|tel:|javascript:)/i.test(x))continue;refs++;if(!fs.existsSync(path.join(root,x)))missing.push(`${f}:${x}`)}}check('Local HTML references',missing.length===0,`${refs} checked; ${missing.length} missing`);
const core=read('js/08-rayo-pricing-admin-module.js'),ops=read('js/42-operations-v10-9-2.js'),catalog=read('js/43-central-catalog-v10-10.js'),config=read('js/config.js'),inv=read('js/32-inventory-cost-control-v10.js'),safety=read('js/38-data-safety-backup-v10-7.js');
check('Build marker 10.10.0',read('js/app-config.js').includes("BUILD:'10.10.0'")&&config.includes("apiVersion:'10.10.0'")&&JSON.parse(read('seed/manifest.json')).build==='10.10.0');
check('Central catalog assets load after v10.9.3 patch',['pricing.html','suppliers.html','inventory.html'].every(f=>{const h=read(f);return h.indexOf('43-central-catalog-v10-10.js')>h.indexOf('42-operations-v10-9-2.js')&&h.includes('07-central-catalog-v10-10.css?v=10.10.0')}));
check('Five item types defined',Array.from(core.matchAll(/(?:MENU_INGREDIENT|MENU_CONSUMABLE|OPERATIONAL_CONSUMABLE|GENERAL_INVENTORY|NON_STOCK):/g)).length>=5&&Object.keys({MENU_INGREDIENT:1,MENU_CONSUMABLE:1,OPERATIONAL_CONSUMABLE:1,GENERAL_INVENTORY:1,NON_STOCK:1}).every(x=>core.includes(x)));
check('Recipe accepts only recipe-capable types',core.includes("['MENU_INGREDIENT','MENU_CONSUMABLE'].includes")&&core.includes('pcRecipeCapable(x)&&'));
check('Non-stock services excluded from inventory',inv.includes("i.itemType!=='NON_STOCK'")&&read('js/09-rayo-inventory-variance-module.js').includes("x.itemType!=='NON_STOCK'"));
check('Operational consumption uses explicit type',read('js/40-rayo-v10-9-comprehensive.js').includes("x.itemType==='OPERATIONAL_CONSUMABLE'"));
check('Catalog delete protects cross-module history',core.includes('ارتباط تأمین')&&core.includes('inventoryRefs')&&core.includes('آن را «غیرفعال» کنید'));
check('Supplier tabs contain no duplicate item master or sync',!ops.slice(ops.indexOf('function supplierTabs'),ops.indexOf('function supplierTab')).includes("['items'")&&!ops.slice(ops.indexOf('function supplierTabs'),ops.indexOf('function supplierTab')).includes("['sync'")&&catalog.includes('اقلام هر تأمین‌کننده'));
check('Supplier relations reference canonical ingredientId',catalog.includes('ingredientId,itemCode:i.code,itemCodeSnapshot:i.code,itemNameSnapshot:i.name')&&ops.includes('r.ingredientId===ing.id'));
check('Migration is explicit and previewed',catalog.includes('previewMigration')&&catalog.includes('applyMigration')&&!catalog.includes('setTimeout(applyMigration')&&!catalog.includes('.then(applyMigration'));
check('Migration downloads both JSON backups first',catalog.indexOf('downloadBackup(bp,bs)')<catalog.indexOf("saveModule('pricing'"));
check('Legacy supplier list is archived, not deleted',catalog.includes('legacyItemsArchived:true')&&!catalog.includes('sup.items=[]'));
check('Failed second save attempts compensating rollback',catalog.includes('if(pricingSaved)try')&&catalog.includes("saveModule('pricing',bp"));
check('Normal module load remains API-only',/async function loadOrBootstrap\(module\)[\s\S]*?return loadModule\(module\);/.test(config));
check('No new backend module required',config.includes("pricing:{arrays:['ingredients'")&&config.includes("suppliers:{arrays:['suppliers','items','supplierItems','purchaseRequests','changeLog']"));
const invNav=inv.slice(inv.indexOf('function nav()'),inv.indexOf('function helpCard')),fixed=['workflow','overview','valuation','receipts','sales','locations','transfer','waste','stock','cost','history','varianceReports'];
check('Inventory stays exactly 12 fixed tabs',fixed.every(x=>invNav.includes(`['${x}'`))&&(invNav.match(/\['(?:workflow|overview|valuation|receipts|sales|locations|transfer|waste|stock|cost|history|varianceReports)'/g)||[]).length===12);
const pricing=JSON.parse(read('seed/pricing-data.seed.json')),sup=JSON.parse(read('seed/suppliers-data.seed.json')),ids=new Set(pricing.ingredients.map(x=>x.id)),codes=new Set(pricing.ingredients.map(x=>String(x.code))),supplierCodes=new Set(sup.items.map(x=>String(x.code))),linked=sup.items.filter(x=>x.source==='pricing'||x.sepidsCode);
check('Canonical seed contains 615 unique items',pricing.ingredients.length===615&&ids.size===615&&codes.size===615);
check('All legacy supplier items now link to catalog',sup.items.length===615&&sup.items.every(x=>x.pricingIngredientId&&ids.has(x.pricingIngredientId)));
check('All 536 Sepidz item codes preserved',linked.length===536&&linked.every(x=>codes.has(String(x.code))));
check('All five types present in seed',['MENU_INGREDIENT','MENU_CONSUMABLE','OPERATIONAL_CONSUMABLE','GENERAL_INVENTORY','NON_STOCK'].every(t=>pricing.ingredients.some(x=>x.itemType===t)));
check('Pizza single is direct menu consumable',pricing.ingredients.some(x=>/سینگل.*پیتزا/.test(x.name)&&x.itemType==='MENU_CONSUMABLE'&&x.recipeCapable===true));
check('Seed initialization remains manager-only',safety.includes('loadOrBootstrap')||config.includes('loadOrBootstrap'));
async function gatewayTest(){let stored={},mode='live',posts=0,seedReads=0;const context={console,setTimeout,clearTimeout,AbortController,URL,structuredClone,location:{pathname:'/suppliers.html'},document:{getElementById:()=>null},fetch:async(url,o={})=>{if(String(url).includes('/seed/'))seedReads++;const module=new URL(url).searchParams.get('module');if((o.method||'GET')==='POST'){posts++;stored=JSON.parse(o.body);mode='stored';return{ok:true,status:200,text:async()=>JSON.stringify(stored)}}const body=mode==='stored'?stored:mode==='live'?{meta:{initialized:true},suppliers:[],items:[],supplierItems:[],purchaseRequests:[],changeLog:[],lists:{}}:{};return{ok:true,status:200,text:async()=>JSON.stringify(body)}}};context.window=context;vm.createContext(context);vm.runInContext(read('js/app-config.js'),context);vm.runInContext(config,context);const g=context.RAYO_API_GATEWAY;await g.loadModule('suppliers');await g.saveModule('suppliers',{meta:{initialized:true},suppliers:[],items:[],supplierItems:[],purchaseRequests:[],changeLog:[],lists:{}},{verify:true});check('Gateway live-load save verifies',posts===1&&!!stored.meta.serverSaveToken);check('Gateway normal load never reads Seed',seedReads===0);mode='empty';await g.loadModule('pricing');let blocked=false;try{await g.saveModule('pricing',{ingredients:[]})}catch(_){blocked=true}check('Gateway blocks uninitialized empty save',blocked)}
gatewayTest().then(()=>{console.log(`PASS ${pass.length}`);pass.forEach(x=>console.log('  ✓ '+x));if(fail.length){console.error(`FAIL ${fail.length}`);fail.forEach(x=>console.error('  ✗ '+x));process.exitCode=1}else console.log('ALL CHECKS PASSED')}).catch(e=>{console.error(e);process.exit(1)});
