(function(){
'use strict';
const MODULE='cashreport';
const USERNAME='sandogh';
const PASSWORD='admin123';
const TYPES=[
  {value:'previousDepositUsed',label:'مصرف بیعانه قبلی برای فروش امروز',sign:1,follow:false},
  {value:'futureDepositReceived',label:'بیعانه دریافت‌شده برای روز آینده',sign:-1,follow:false},
  {value:'customerReceivable',label:'طلب از مشتری / پرداخت‌نشده',sign:1,follow:true},
  {value:'oldReceivableReceived',label:'دریافت طلب مربوط به روزهای قبل',sign:-1,follow:false},
  {value:'refundOrCorrection',label:'برگشت وجه یا اصلاح پرداخت',sign:1,follow:false},
  {value:'otherIncrease',label:'سایر موارد افزاینده مغایرت',sign:1,follow:false},
  {value:'otherDecrease',label:'سایر موارد کاهنده مغایرت',sign:-1,follow:false}
];
const EMPTY={meta:{schemaVersion:'1.0.0',module:'Rayo Cash Report',restaurant:'کافه‌رستوران رایو',currency:'ریال',updatedAt:null},settings:{inputCurrency:'ریال',displayCurrency:'تومان',discrepancyLimit:1000000},cashiers:[],reports:[],changeLog:[]};
let state=normalize(EMPTY),currentCashier=null,currentReportId='',reportReadOnly=false,reportSubmitting=false,reportController=null,pendingMutation=null;
const REPORT_COLLECTION='reports',REPORT_ID_FIELD='id',REPORT_DATE_FIELD='date';
const $=id=>document.getElementById(id);
function obj(x){return x&&typeof x==='object'&&!Array.isArray(x)?x:{}}
function arr(x){return Array.isArray(x)?x:[]}
function clone(x){return JSON.parse(JSON.stringify(x))}
function num(v){const n=Number(String(v??'').replace(/[٬,\s]/g,''));return Number.isFinite(n)?n:0}
function text(v){return String(v??'').trim()}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function now(){return new Date().toISOString()}
function todayJ(){try{const p=new Intl.DateTimeFormat('en-CA-u-ca-persian',{year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const o={};p.forEach(x=>o[x.type]=x.value);return `${o.year}/${o.month}/${o.day}`}catch(_){return''}}
function uid(prefix,list){let max=0;arr(list).forEach(x=>{const m=String(x.id||'').match(/(\d+)$/);if(m)max=Math.max(max,+m[1])});return `${prefix}-${String(max+1).padStart(4,'0')}`}
function ciGet(o,name){if(!obj(o))return undefined;const k=Object.keys(o).find(x=>String(x).toLowerCase()===String(name).toLowerCase());return k==null?undefined:o[k]}
function parsePayload(value){let x=value;for(let i=0;i<8;i++){if(typeof x==='string'){const t=x.trim();if(!t)return{};try{x=JSON.parse(t);continue}catch(_){return x}}if(x&&typeof x==='object'&&!Array.isArray(x)){const allowed=['data','result','value','payload','content','json','cashreport','cashreports'];const key=Object.keys(x).find(k=>allowed.includes(String(k).toLowerCase()));if(key&&x[key]!==x){x=x[key];continue}}break}return x}
function normalize(raw){const d=obj(parsePayload(raw)),x={...clone(EMPTY),...d};x.meta={...EMPTY.meta,...obj(ciGet(d,'meta'))};x.settings={...EMPTY.settings,...obj(ciGet(d,'settings'))};x.cashiers=arr(ciGet(d,'cashiers')).map((c,i)=>({id:ciGet(c,'id')||`CASHIER-${String(i+1).padStart(4,'0')}`,name:ciGet(c,'name')||'',personnelId:ciGet(c,'personnelId')||'',status:ciGet(c,'status')||'فعال',notes:ciGet(c,'notes')||''}));x.reports=arr(ciGet(d,'reports')).map((r,i)=>normalizeReport(r,i));x.changeLog=arr(ciGet(d,'changeLog'));return x}
function normalizeReport(r,i=0){const x={...obj(r),id:r?.id||`CASH-${String(i+1).padStart(4,'0')}`};['netReceivable','tipDelivery','tipValet','tipHall','cardToCard','cash','receiptCount','snappAmount','snappReceiptCount'].forEach(k=>x[k]=num(x[k]));for(let p=1;p<=6;p++)x[`pos${p}`]=num(x[`pos${p}`]);x.otherTransactions=arr(x.otherTransactions).map((a,j)=>({id:a.id||`ADJ-${j+1}`,type:a.type||'otherIncrease',title:a.title||'',amount:num(a.amount),sign:Number(a.sign)===-1?-1:1,customerName:a.customerName||'',phone:a.phone||'',dueDate:a.dueDate||'',followUpRequired:a.followUpRequired===true||a.followUpRequired==='بله',status:a.status||'باز',notes:a.notes||'',settledAt:a.settledAt||'',settlementNote:a.settlementNote||''}));return {...x,...calc(x)}}
function calc(r){const m=window.RayoCashVariance.calculate(r);if(!m.valid)return m;const totalSales=num(r.netReceivable)+num(r.snappAmount),totalReceiptCount=num(r.receiptCount)+num(r.snappReceiptCount);return{...m,totalSales,totalReceiptCount,averageReceipt:num(r.receiptCount)?num(r.netReceivable)/num(r.receiptCount):0,averageSnappReceipt:num(r.snappReceiptCount)?num(r.snappAmount)/num(r.snappReceiptCount):0,overallAverage:totalReceiptCount?totalSales/totalReceiptCount:0}}
function money(v){return `${Math.round(num(v)).toLocaleString('fa-IR')} ریال`}
function signed(v){const n=num(v);return `<span class="${n<0?'negative':n>0?'positive':''}">${n>0?'+':''}${money(n)}</span>`}
function popup(message,error=false){const d=document.createElement('div');d.className=`popup${error?' error':''}`;d.textContent=message;$('popup').appendChild(d);setTimeout(()=>d.remove(),error?6500:3500)}
function loading(v){$('loading').classList.toggle('show',!!v)}
async function fetchTimeout(url,options={},ms=10000){const c=new AbortController(),timer=setTimeout(()=>c.abort(),ms);try{return await fetch(url,{...options,signal:c.signal})}catch(e){if(e?.name==='AbortError')throw Error('Timeout');if(String(e?.message||'').toLowerCase().includes('failed to fetch'))throw Error('CORS یا ارتباط شبکه');throw e}finally{clearTimeout(timer)}}
async function responseJson(r){const t=await r.text();if(!r.ok)throw Error(`HTTP ${r.status}${t?` — ${t.slice(0,180)}`:''}`);if(!t.trim())throw Error('پاسخ خالی است');const x=parsePayload(t);if(!x||typeof x!=='object'||Array.isArray(x))throw Error('ساختار JSON گزارش صندوق معتبر نیست');const backendClass=ciGet(x,'ClassName')||ciGet(x,'ExceptionType');const backendMessage=ciGet(x,'Message')||ciGet(x,'message')||ciGet(x,'ExceptionMessage');if(backendClass||backendMessage&&Object.keys(x).some(k=>['stacktracestring','remotestacktracestring','innerexception','helplink'].includes(String(k).toLowerCase()))){throw Error(`Backend ماژول cashreport را نپذیرفت${backendMessage?`: ${backendMessage}`:''}`)}return normalize(x)}
async function queryItems(collection,options={}){const first=await window.RAYO_API_GATEWAY.queryCollection({module:MODULE,collection,page:1,pageSize:500,...options}),items=[...first.items];for(let page=2;page<=first.totalPages;page++){const next=await window.RAYO_API_GATEWAY.queryCollection({module:MODULE,collection,page,pageSize:500,...options});items.push(...next.items)}return items}
async function loadApi(){if(!window.RAYO_API_GATEWAY?.queryCollection)throw Error('تنظیمات API بارگذاری نشده است');const cashiers=await queryItems('cashiers',{filters:{status:'فعال'},sortBy:'name',descending:false,includeArchived:false});return normalize({...EMPTY,cashiers,reports:state.reports})}
async function loadState(){return loadApi()}
async function postState(data){
  data.meta={...obj(data.meta),updatedAt:now(),serverSaveToken:`CASH-${Date.now()}-${Math.random().toString(36).slice(2,8)}`};
  await window.RAYO_API_GATEWAY.saveModule(MODULE,data,{verify:true});
  return true;
}

async function saveReport(report){const old=state.reports.find(x=>x.id===report.id)||state.reports.find(x=>x.date===report.date);if(old){const oldAdjustments=new Map(arr(old.otherTransactions).map(x=>[x.id,x]));report.otherTransactions=arr(report.otherTransactions).map(x=>oldAdjustments.get(x.id)?.status==='تسویه‌شده'?{...x,status:'تسویه‌شده',settledAt:oldAdjustments.get(x.id).settledAt,settlementNote:oldAdjustments.get(x.id).settlementNote}:x)}const fingerprint=JSON.stringify({id:old?.id||'',report});if(!pendingMutation||pendingMutation.fingerprint!==fingerprint)pendingMutation={fingerprint,requestId:RAYO_API_GATEWAY.createRequestId(),recordId:old?.id||`CASH-${report.date.replace(/\D/g,'')}-${RAYO_API_GATEWAY.createRequestId()}`,createdAt:now()};const data=old?{...old,...report,id:pendingMutation.recordId,updatedAt:now(),updatedBy:`صندوقدار: ${currentCashier.name}`}:{...report,id:pendingMutation.recordId,registeredByType:'cashier',registeredByName:`صندوقدار: ${currentCashier.name}`,createdAt:pendingMutation.createdAt,updatedAt:now(),managerReview:'بررسی نشده'};await RAYO_API_GATEWAY.mutateRecord({module:MODULE,collection:REPORT_COLLECTION,operation:old?'update':'insert',recordId:pendingMutation.recordId,idField:REPORT_ID_FIELD,requestId:pendingMutation.requestId,data});pendingMutation=null;await loadExistingForDate(true);return true}
function fillCashiers(){state=normalize(state||EMPTY);const list=state.cashiers.filter(x=>x.status==='فعال');$('loginCashier').innerHTML='<option value="">انتخاب کنید</option>'+list.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('');if(!list.length)popup('ابتدا صندوقدارها را در پنل مدیریت تعریف کنید',true)}
function login(e){e.preventDefault();state=normalize(state||EMPTY);const cashier=state.cashiers.find(x=>x.id===$('loginCashier').value&&x.status==='فعال');if(!cashier)return popup('صندوقدار را انتخاب کنید',true);if($('username').value!==USERNAME||$('password').value!==PASSWORD)return popup('نام کاربری یا رمز عبور اشتباه است',true);currentCashier=cashier;sessionStorage.setItem('rayoCashierId',cashier.id);$('cashierLabel').textContent=cashier.name;$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');resetForm();loadExistingForDate()}
function logout(){sessionStorage.removeItem('rayoCashierId');currentCashier=null;$('appView').classList.add('hidden');$('loginView').classList.remove('hidden');$('password').value=''}
function typeInfo(type){return TYPES.find(x=>x.value===type)||TYPES[5]}
function adjustmentRow(a={}){const t=typeInfo(a.type),sign=Number(a.sign)===-1?-1:(a.sign==null?t.sign:1);return `<div class="adjust-row" data-id="${esc(a.id||'')}"><label>نوع<select class="a-type">${TYPES.map(x=>`<option value="${x.value}" ${x.value===(a.type||t.value)?'selected':''}>${x.label}</option>`).join('')}</select></label><label>شرح<input class="a-title" value="${esc(a.title||'')}"></label><label>مبلغ (ریال)<input class="a-amount" type="number" min="0" value="${num(a.amount)}"></label><label>اثر<select class="a-sign"><option value="1" ${sign===1?'selected':''}>افزایش</option><option value="-1" ${sign===-1?'selected':''}>کاهش</option></select></label><label>نام مشتری<input class="a-customer" value="${esc(a.customerName||'')}"></label><label>تلفن<input class="a-phone" value="${esc(a.phone||'')}"></label><label>موعد پیگیری<input class="a-due" value="${esc(a.dueDate||'')}"></label><label class="check"><input class="a-follow" type="checkbox" ${a.followUpRequired||t.follow?'checked':''}> پیگیری</label><label class="wide">توضیحات<input class="a-notes" value="${esc(a.notes||'')}"></label><button type="button" class="danger a-remove">حذف</button></div>`}
function addAdjustment(a={type:'otherIncrease',sign:1}){$('adjustments').insertAdjacentHTML('beforeend',adjustmentRow(a));bindAdjustmentRows();updateSummary()}
function bindAdjustmentRows(){document.querySelectorAll('.adjust-row').forEach(row=>{row.querySelectorAll('input,select').forEach(x=>x.oninput=updateSummary);row.querySelector('.a-type').onchange=e=>{const t=typeInfo(e.target.value);row.querySelector('.a-sign').value=String(t.sign);row.querySelector('.a-follow').checked=t.follow;updateSummary()};row.querySelector('.a-remove').onclick=()=>{row.remove();updateSummary()}})}
function val(id){return num($(id).value)}
function readAdjustments(){return [...document.querySelectorAll('.adjust-row')].map((row,i)=>({id:row.dataset.id||`ADJ-${Date.now()}-${i+1}`,type:row.querySelector('.a-type').value,title:text(row.querySelector('.a-title').value),amount:num(row.querySelector('.a-amount').value),sign:Number(row.querySelector('.a-sign').value)===-1?-1:1,customerName:text(row.querySelector('.a-customer').value),phone:text(row.querySelector('.a-phone').value),dueDate:text(row.querySelector('.a-due').value),followUpRequired:row.querySelector('.a-follow').checked,status:'باز',notes:text(row.querySelector('.a-notes').value)})).filter(x=>x.amount||x.title||x.customerName)}
function readForm(){const r={id:currentReportId,date:text($('reportDate').value),cashierId:currentCashier?.id||'',cashierName:currentCashier?.name||'',netReceivable:val('netReceivable'),tipDelivery:val('tipDelivery'),tipValet:val('tipValet'),tipHall:val('tipHall'),cardToCard:val('cardToCard'),cash:val('cash'),receiptCount:val('receiptCount'),snappAmount:val('snappAmount'),snappReceiptCount:val('snappReceiptCount'),notes:text($('notes').value),otherTransactions:readAdjustments()};for(let i=1;i<=6;i++)r[`pos${i}`]=val(`pos${i}`);return {...r,...calc(r)}}
function updateSummary(){const m=calc(readForm());$('summary').innerHTML=m.valid===false?'<div class="error">مبلغ نامعتبر است؛ مقدار نامعتبر صفر محسوب نمی‌شود.</div>':`<div><span>جمع کارتخوان‌ها</span><b>${money(m.posTotal)}</b></div><div><span>جمع وصول</span><b>${money(m.actualReceived)}</b></div><div><span>محاسبه</span><b>${money(m.actualReceived)} − (${money(m.netReceivable)} + ${money(m.tipsInThisCashbox)})</b></div><div class="final"><span>${m.status}</span><b>${signed(m.initialVariance)}</b></div><div><span>جمع اصلاحات</span><b>${signed(m.adjustmentsTotal)}</b></div><div><span>مغایرت نهایی</span><b>${signed(m.finalVariance)}</b></div><div><span>کل فروش با اسنپ</span><b>${money(m.totalSales)}</b></div>`}
function clearValues(keepDate=true){const d=keepDate?$('reportDate').value:todayJ();['netReceivable','tipDelivery','tipValet','tipHall','pos1','pos2','pos3','pos4','pos5','pos6','cardToCard','cash','receiptCount','snappAmount','snappReceiptCount'].forEach(id=>$(id).value=0);$('notes').value='';$('adjustments').innerHTML='';$('reportDate').value=d;currentReportId='';$('formTitle').textContent='گزارش روزانه';updateSummary()}
function resetForm(){clearValues(false)}
function fillReport(r){currentReportId=r.id||'';$('formTitle').textContent=`ویرایش گزارش ${r.date}`;$('reportDate').value=r.date||todayJ();['netReceivable','tipDelivery','tipValet','tipHall','pos1','pos2','pos3','pos4','pos5','pos6','cardToCard','cash','receiptCount','snappAmount','snappReceiptCount'].forEach(id=>$(id).value=num(r[id]));$('notes').value=r.notes||'';$('adjustments').innerHTML=arr(r.otherTransactions).map(adjustmentRow).join('');bindAdjustmentRows();updateSummary()}
async function loadExistingForDate(silent=false){const date=text($('reportDate').value);if(!/^\d{4}\/\d{2}\/\d{2}$/.test(date))return;reportController?.abort();const controller=new AbortController();reportController=controller;try{const iso=date.replaceAll('/','-'),q=await RAYO_API_GATEWAY.queryCollection({module:MODULE,collection:REPORT_COLLECTION,filters:{},dateField:REPORT_DATE_FIELD,from:iso,to:iso,sortBy:REPORT_DATE_FIELD,descending:true,includeArchived:false,page:1,pageSize:2,signal:controller.signal});state.reports=arr(q.items).map(normalizeReport);reportReadOnly=false;const r=state.reports.find(x=>x.date===date);if(r){fillReport(r);if(!silent)popup('گزارش این تاریخ قبلاً ثبت شده و برای ویرایش بارگذاری شد')}else{clearValues(true);$('reportDate').value=date}}catch(e){if(e.name!=='AbortError'){reportReadOnly=true;popup(e.message||'دریافت گزارش این تاریخ انجام نشد؛ فرم فقط‌خواندنی است.',true)}}finally{if(reportController===controller)reportController=null}}
async function submit(e){e.preventDefault();if(!currentCashier)return popup('ابتدا وارد شوید',true);if(reportReadOnly||reportSubmitting)return popup('تا دریافت معتبر اطلاعات، ثبت گزارش غیرفعال است.',true);const r=readForm();if(!/^\d{4}\/\d{2}\/\d{2}$/.test(r.date))return popup('تاریخ را به شکل 1405/05/13 وارد کنید',true);const button=e.submitter||document.querySelector('#cashForm button[type="submit"]');reportSubmitting=true;if(button)button.disabled=true;loading(true);try{await saveReport(r);popup('گزارش صندوق با موفقیت روی سرور ذخیره شد');clearValues(true)}catch(err){if(err.code==='version_conflict'){popup('گزارش هم‌زمان تغییر کرده است؛ اطلاعات فرم شما حفظ شد.',true);if(confirm('نسخه جدید این تاریخ دریافت شود؟'))await loadExistingForDate(true)}else popup(err.message||'ذخیره گزارش انجام نشد؛ تلاش مجدد با همان شناسه درخواست انجام می‌شود.',true)}finally{reportSubmitting=false;if(button)button.disabled=false;loading(false)}}
async function refresh(){loading(true);try{state=await loadState();fillCashiers();loadExistingForDate();popup('اطلاعات بروزرسانی شد')}catch(e){popup(e.message,true)}finally{loading(false)}}
async function init(){try{state=await loadState();fillCashiers();$('reportDate').value=todayJ();updateSummary();const saved=sessionStorage.getItem('rayoCashierId'),c=state.cashiers.find(x=>x.id===saved&&x.status==='فعال');if(c){currentCashier=c;$('cashierLabel').textContent=c.name;$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');await loadExistingForDate()}}catch(e){reportReadOnly=true;popup(e.message||'بارگذاری انجام نشد؛ ذخیره غیرفعال است.',true)}finally{loading(false)}}
$('loginForm').addEventListener('submit',login);$('logoutBtn').addEventListener('click',logout);$('cashForm').addEventListener('submit',submit);$('addAdjustment').addEventListener('click',()=>addAdjustment());$('reloadBtn').addEventListener('click',refresh);$('reportDate').addEventListener('change',loadExistingForDate);document.querySelectorAll('#cashForm input').forEach(x=>x.addEventListener('input',updateSummary));window.addEventListener('pagehide',()=>reportController?.abort(),{once:true});init();
})();
